
' Generated by MyGeneration Version # (1.1.7.7)

Imports System

Namespace EasyObjects.Tests.Oracle

    Public Class EmployeeDeptHist
        Inherits _EmployeeDeptHist

    End Class

End Namespace
