CREATE TABLE "MNOONA01"."AGGREGATETEST" 
( 
	"ID" NUMBER, 
	"DEPARTMENTID" NUMBER, 
	"FIRSTNAME" VARCHAR2(25), 
	"LASTNAME" VARCHAR2(15), 
	"AGE" NUMBER, 
	"HIREDATE" DATE, 
	"SALARY" NUMBER(8, 4), 
	"ISACTIVE" NUMBER(2), 
	"TS" NUMBER, 
	CHECK ("ID" IS NOT NULL) VALIDATE , 
	CHECK ("TS" IS NOT NULL) VALIDATE , 
	PRIMARY KEY ("ID") VALIDATE 
) 
TABLESPACE "SYSTEM" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE 
( INITIAL 64K FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT ) 
LOGGING ;

CREATE SEQUENCE  "MNOONA01"."AGGTESTID"  MINVALUE 50 MAXVALUE 1.00000000000000E+27 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;

CREATE TABLE "MNOONA01"."CUSTOMERS"
(
	"CUSTOMERID" CHAR(5),
	"COMPANYNAME" VARCHAR2(40),
	"CONTACTNAME" VARCHAR2(30),
	"CONTACTTITLE" VARCHAR2(30),
	"ADDRESS" VARCHAR2(60),
	"CITY" VARCHAR2(15),
	"REGION" VARCHAR2(15),
	"POSTALCODE" VARCHAR2(10),
	"COUNTRY" VARCHAR2(15),
	"PHONE" VARCHAR2(24),
	"FAX" VARCHAR2(24),
	CHECK ("CUSTOMERID" IS NOT NULL) VALIDATE , 
	PRIMARY KEY ("CUSTOMERID") VALIDATE 
)
TABLESPACE "SYSTEM" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE 
( INITIAL 64K FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT ) 
LOGGING ;

CREATE TABLE "MNOONA01"."EMPLOYEEDEPTHIST"
(
	"EMPLOYEEID" NUMBER,
	"DEPARTMENTID" NUMBER,
	"STARTDATE" DATE,
	"ENDDATE" DATE,
	"MODIFIEDDATE" DATE,
	CHECK ("EMPLOYEEID" IS NOT NULL) VALIDATE , 
	CHECK ("DEPARTMENTID" IS NOT NULL) VALIDATE , 
	PRIMARY KEY ("EMPLOYEEID", "DEPARTMENTID") VALIDATE 
)
TABLESPACE "SYSTEM" PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 STORAGE 
( INITIAL 64K FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT ) 
LOGGING ;

CREATE OR REPLACE VIEW FULLNAMEVIEW AS
SELECT AGGREGATETEST.LASTNAME||', '||AGGREGATETEST.FIRSTNAME AS "FULLNAME",
        AGGREGATETEST.DEPARTMENTID,
        AGGREGATETEST.HIREDATE,
        AGGREGATETEST.SALARY,
        AGGREGATETEST.ISACTIVE
FROM AGGREGATETEST
WHERE AGGREGATETEST.ISACTIVE = 1;