
' Generated by MyGeneration Version # (1.1.6.0)

Imports System

NameSpace EasyObjects.Tests.SQL

Public Class EmployeeDepartmentHistory 
	Inherits _EmployeeDepartmentHistory

End Class

End NameSpace
