'===============================================================================
'  Generated From - VbNet_EasyObject_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  
'  This object is 'MustInherit' which means you need to inherit from it to be able
'  to instantiate it.  This is very easily done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  Public Class YourObject 
'      Inherits _YourObject
'
'  End Class
'
'===============================================================================

' EasyObjects.NET version 1.1
' Generated by MyGeneration Version # (1.1.6.0)

Imports System
Imports System.Data
Imports System.Configuration
Imports System.Collections
Imports System.Collections.Specialized
Imports System.Xml
Imports System.IO

Imports Microsoft.Practices.EnterpriseLibrary.Data
Imports NCI.EasyObjects


#Region " Schema "

Public Class ProductsSchema
	Inherits NCI.EasyObjects.Schema

    Private Shared _entries As ArrayList
	Public Shared ProductID As New SchemaItem("ProductID", DbType.Int32, True, False, False, True, True, False)
	Public Shared ProductName As New SchemaItem("ProductName", DbType.String, SchemaItemJustify.None, 40, False, False, False, False)
	Public Shared SupplierID As New SchemaItem("SupplierID", DbType.Int32, False, True, False, False, True, False)
	Public Shared CategoryID As New SchemaItem("CategoryID", DbType.Int32, False, True, False, False, True, False)
	Public Shared QuantityPerUnit As New SchemaItem("QuantityPerUnit", DbType.String, SchemaItemJustify.None, 20, True, False, False, False)
	Public Shared UnitPrice As New SchemaItem("UnitPrice", DbType.Currency, False, True, False, False, False, True)
	Public Shared UnitsInStock As New SchemaItem("UnitsInStock", DbType.Int16, False, True, False, False, False, True)
	Public Shared UnitsOnOrder As New SchemaItem("UnitsOnOrder", DbType.Int16, False, True, False, False, False, True)
	Public Shared ReorderLevel As New SchemaItem("ReorderLevel", DbType.Int16, False, True, False, False, False, True)
	Public Shared Discontinued As New SchemaItem("Discontinued", DbType.Boolean, False, False, False, False, False, True)

    Public Overrides ReadOnly Property SchemaEntries() As ArrayList
        Get
            If _entries Is Nothing Then
                _entries = New ArrayList()
				_entries.Add(ProductsSchema.ProductID)
				_entries.Add(ProductsSchema.ProductName)
				_entries.Add(ProductsSchema.SupplierID)
				_entries.Add(ProductsSchema.CategoryID)
				_entries.Add(ProductsSchema.QuantityPerUnit)
				_entries.Add(ProductsSchema.UnitPrice)
				_entries.Add(ProductsSchema.UnitsInStock)
				_entries.Add(ProductsSchema.UnitsOnOrder)
				_entries.Add(ProductsSchema.ReorderLevel)
				_entries.Add(ProductsSchema.Discontinued)

            End If
            Return _entries
        End Get
    End Property

End Class

#End Region

Public MustInherit Class _Products
    Inherits NCI.EasyObjects.EasyObject

    Sub New()
        Dim _schema As New ProductsSchema()
        Me.SchemaEntries = _schema.SchemaEntries
		Me.SchemaGlobal = "dbo"
    End Sub

	Public Overrides Sub FlushData()
		Me._whereClause = Nothing
		Me._aggregateClause = Nothing
		MyBase.FlushData()
	End Sub
		
	''' <summary>
	''' Loads the business object with info from the database, based on the requested primary key.
	''' </summary>
	''' <param name="ProductID"></param>
	''' <returns>A Boolean indicating success or failure of the query</returns>
	Public Function LoadByPrimaryKey(ByVal ProductID As Integer) As Boolean
		
		Select Case Me.DefaultCommandType
			Case CommandType.StoredProcedure
				Dim parameters As ListDictionary = New ListDictionary

				' Add in parameters
				parameters.Add(ProductsSchema.ProductID.FieldName, ProductID)

				Return MyBase.LoadFromSql(Me.SchemaStoredProcedureWithSeparator & "daab_GetProducts", parameters, CommandType.StoredProcedure)
				
			Case CommandType.Text
                Me.Query.ClearAll()
                Me.Where.WhereClauseReset()
				Me.Where.ProductID.Value = ProductID
				Return Me.Query.Load()

			Case Else
				Throw New ArgumentException("Invalid CommandType", "commandType")
				
		End Select
		
	End Function

    ''' <summary>
    ''' Loads all records from the table.
    ''' </summary>
    ''' <returns>A Boolean indicating success or failure of the query</returns>
    Public Function LoadAll() As Boolean
	
		Select Case Me.DefaultCommandType
		
			Case CommandType.StoredProcedure
				Dim parameters As ListDictionary = Nothing
				Return MyBase.LoadFromSql(Me.SchemaStoredProcedureWithSeparator & "daab_GetAllProducts", parameters, CommandType.StoredProcedure)
				
			Case CommandType.Text
                Me.Query.ClearAll()
                Me.Where.WhereClauseReset()
				Return Me.Query.Load()
			
			Case Else
				Throw New ArgumentException("Invalid CommandType", "commandType")
				
		End Select

    End Function

    ''' <summary>
    ''' Adds a new record to the internal table.
    ''' </summary>
	Public Overrides Sub AddNew()
		MyBase.AddNew()

	End Sub

    Protected Overloads Overrides Function GetInsertCommand(commandType As CommandType) As DBCommandWrapper
	
		Dim dbCommandWrapper As DBCommandWrapper
		
        ' Create the Database object, using the default database service. The
        ' default database service is determined through configuration.
        Dim db As Database = GetDatabase()
	
		Select Case commandType
		
			Case CommandType.StoredProcedure
				Dim sqlCommand As String = Me.SchemaStoredProcedureWithSeparator & "daab_AddProducts"
				dbCommandWrapper = db.GetStoredProcCommandWrapper(sqlCommand)
		
				dbCommandWrapper.AddParameter("ProductID", DbType.Int32, 0, ParameterDirection.Output, true, 0, 0, "ProductID", DataRowVersion.Default, Convert.DBNull)
				CreateParameters(dbCommandWrapper)

			Case CommandType.Text
                Me.Query.ClearAll()
                Me.Where.WhereClauseReset()
				For Each item As SchemaItem In Me.SchemaEntries
					If Not item.IsComputed Then
						If (item.IsAutoKey And Me.IdentityInsert) Or Not item.IsAutoKey Then
							Me.Query.AddInsertColumn(item)
						End If
					End If
				Next
				dbCommandWrapper = Me.Query.GetInsertCommandWrapper()

				dbCommandWrapper.Command.Parameters.Clear()
				If Me.IdentityInsert Then
					dbCommandWrapper.AddInParameter("ProductID", DbType.Int32, "ProductID", DataRowVersion.Default)
				Else
					dbCommandWrapper.AddParameter("ProductID", DbType.Int32, 0, ParameterDirection.Output, true, 0, 0, "ProductID", DataRowVersion.Default, Convert.DBNull)
				End If

				CreateParameters(dbCommandWrapper)
				
			Case Else
				Throw New ArgumentException("Invalid CommandType", "commandType")
				
		End Select

        Return dbCommandWrapper

    End Function

    Protected Overloads Overrides Function GetUpdateCommand(commandType As CommandType) As DBCommandWrapper
	
		Dim dbCommandWrapper As DBCommandWrapper

        ' Create the Database object, using the default database service. The
        ' default database service is determined through configuration.
        Dim db As Database = GetDatabase()
	
		Select Case commandType
		
			Case CommandType.StoredProcedure
				Dim sqlCommand As String = Me.SchemaStoredProcedureWithSeparator & "daab_UpdateProducts"
				dbCommandWrapper = db.GetStoredProcCommandWrapper(sqlCommand)
				
				dbCommandWrapper.AddInParameter("ProductID", DbType.Int32, "ProductID", DataRowVersion.Current)
				CreateParameters(dbCommandWrapper)

			Case CommandType.Text
                Me.Query.ClearAll()
				For Each item As SchemaItem In Me.SchemaEntries
					If Not (item.IsAutoKey OrElse item.IsComputed)
						Me.Query.AddUpdateColumn(item)
					End If
				Next

				Me.Where.WhereClauseReset()
				Me.Where.ProductID.Operator = WhereParameter.Operand.Equal
				dbCommandWrapper = Me.Query.GetUpdateCommandWrapper()

				dbCommandWrapper.Command.Parameters.Clear()
				CreateParameters(dbCommandWrapper)
				dbCommandWrapper.AddInParameter("ProductID", DbType.Int32, "ProductID", DataRowVersion.Current)

			Case Else
				Throw New ArgumentException("Invalid CommandType", "commandType")
				
		End Select

        Return dbCommandWrapper

    End Function

    Protected Overloads Overrides Function GetDeleteCommand(commandType As CommandType) As DBCommandWrapper
	
		Dim dbCommandWrapper As DBCommandWrapper

        ' Create the Database object, using the default database service. The
        ' default database service is determined through configuration.
        Dim db As Database = GetDatabase()
	
		Select Case commandType
		
			Case CommandType.StoredProcedure
				Dim sqlCommand As String = Me.SchemaStoredProcedureWithSeparator & "daab_DeleteProducts"
				dbCommandWrapper = db.GetStoredProcCommandWrapper(sqlCommand)
		
				' Add primary key parameters
				dbCommandWrapper.AddInParameter("ProductID", DbType.Int32, "ProductID", DataRowVersion.Current)

			Case CommandType.Text
                Me.Query.ClearAll()
                Me.Where.WhereClauseReset()
				Me.Where.ProductID.Operator = WhereParameter.Operand.Equal
				dbCommandWrapper = Me.Query.GetDeleteCommandWrapper()

				dbCommandWrapper.Command.Parameters.Clear()
				dbCommandWrapper.AddInParameter("ProductID", DbType.Int32, "ProductID", DataRowVersion.Current)

			Case Else
				Throw New ArgumentException("Invalid CommandType", "commandType")
				
		End Select

        Return dbCommandWrapper

    End Function

    Private Sub CreateParameters(ByVal dbCommandWrapper As DBCommandWrapper)
		
		dbCommandWrapper.AddInParameter("ProductName", DbType.String, "ProductName", DataRowVersion.Current)
		dbCommandWrapper.AddInParameter("SupplierID", DbType.Int32, "SupplierID", DataRowVersion.Current)
		dbCommandWrapper.AddInParameter("CategoryID", DbType.Int32, "CategoryID", DataRowVersion.Current)
		dbCommandWrapper.AddInParameter("QuantityPerUnit", DbType.String, "QuantityPerUnit", DataRowVersion.Current)
		dbCommandWrapper.AddInParameter("UnitPrice", DbType.Currency, "UnitPrice", DataRowVersion.Current)
		dbCommandWrapper.AddInParameter("UnitsInStock", DbType.Int16, "UnitsInStock", DataRowVersion.Current)
		dbCommandWrapper.AddInParameter("UnitsOnOrder", DbType.Int16, "UnitsOnOrder", DataRowVersion.Current)
		dbCommandWrapper.AddInParameter("ReorderLevel", DbType.Int16, "ReorderLevel", DataRowVersion.Current)
		dbCommandWrapper.AddInParameter("Discontinued", DbType.Boolean, "Discontinued", DataRowVersion.Current)

    End Sub

#Region " Properties "

	Public Overridable Property ProductID() As Integer
        Get
			Return Me.GetInteger(ProductsSchema.ProductID.FieldName)
      End Get
        Set(ByVal Value As Integer)
			Me.SetInteger(ProductsSchema.ProductID.FieldName, Value)
      End Set
    End Property

	Public Overridable Property ProductName() As String
        Get
			Return Me.GetString(ProductsSchema.ProductName.FieldName)
      End Get
        Set(ByVal Value As String)
			Me.SetString(ProductsSchema.ProductName.FieldName, Value)
      End Set
    End Property

	Public Overridable Property SupplierID() As Integer
        Get
			Return Me.GetInteger(ProductsSchema.SupplierID.FieldName)
      End Get
        Set(ByVal Value As Integer)
			Me.SetInteger(ProductsSchema.SupplierID.FieldName, Value)
      End Set
    End Property

	Public Overridable Property CategoryID() As Integer
        Get
			Return Me.GetInteger(ProductsSchema.CategoryID.FieldName)
      End Get
        Set(ByVal Value As Integer)
			Me.SetInteger(ProductsSchema.CategoryID.FieldName, Value)
      End Set
    End Property

	Public Overridable Property QuantityPerUnit() As String
        Get
			Return Me.GetString(ProductsSchema.QuantityPerUnit.FieldName)
      End Get
        Set(ByVal Value As String)
			Me.SetString(ProductsSchema.QuantityPerUnit.FieldName, Value)
      End Set
    End Property

	Public Overridable Property UnitPrice() As Decimal
        Get
			Return Me.GetDecimal(ProductsSchema.UnitPrice.FieldName)
      End Get
        Set(ByVal Value As Decimal)
			Me.SetDecimal(ProductsSchema.UnitPrice.FieldName, Value)
      End Set
    End Property

	Public Overridable Property UnitsInStock() As Short
        Get
			Return Me.GetShort(ProductsSchema.UnitsInStock.FieldName)
      End Get
        Set(ByVal Value As Short)
			Me.SetShort(ProductsSchema.UnitsInStock.FieldName, Value)
      End Set
    End Property

	Public Overridable Property UnitsOnOrder() As Short
        Get
			Return Me.GetShort(ProductsSchema.UnitsOnOrder.FieldName)
      End Get
        Set(ByVal Value As Short)
			Me.SetShort(ProductsSchema.UnitsOnOrder.FieldName, Value)
      End Set
    End Property

	Public Overridable Property ReorderLevel() As Short
        Get
			Return Me.GetShort(ProductsSchema.ReorderLevel.FieldName)
      End Get
        Set(ByVal Value As Short)
			Me.SetShort(ProductsSchema.ReorderLevel.FieldName, Value)
      End Set
    End Property

	Public Overridable Property Discontinued() As Boolean
        Get
			Return Me.GetBoolean(ProductsSchema.Discontinued.FieldName)
      End Get
        Set(ByVal Value As Boolean)
			Me.SetBoolean(ProductsSchema.Discontinued.FieldName, Value)
      End Set
    End Property

    Public Overrides ReadOnly Property TableName() As String
        Get
            Return "Products"
        End Get
    End Property

#End Region

#Region " String Properties "
		Public Overridable Property s_ProductID As String
			Get
				If Me.IsColumnNull(ProductsSchema.ProductID.FieldName) Then
					Return String.Empty
				Else
					Return MyBase.GetIntegerAsString(ProductsSchema.ProductID.FieldName)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ProductsSchema.ProductID.FieldName)
				Else
					Me.ProductID = MyBase.SetIntegerAsString(ProductsSchema.ProductID.FieldName, Value)
				End If
			End Set
		End Property

		Public Overridable Property s_ProductName As String
			Get
				If Me.IsColumnNull(ProductsSchema.ProductName.FieldName) Then
					Return String.Empty
				Else
					Return MyBase.GetStringAsString(ProductsSchema.ProductName.FieldName)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ProductsSchema.ProductName.FieldName)
				Else
					Me.ProductName = MyBase.SetStringAsString(ProductsSchema.ProductName.FieldName, Value)
				End If
			End Set
		End Property

		Public Overridable Property s_SupplierID As String
			Get
				If Me.IsColumnNull(ProductsSchema.SupplierID.FieldName) Then
					Return String.Empty
				Else
					Return MyBase.GetIntegerAsString(ProductsSchema.SupplierID.FieldName)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ProductsSchema.SupplierID.FieldName)
				Else
					Me.SupplierID = MyBase.SetIntegerAsString(ProductsSchema.SupplierID.FieldName, Value)
				End If
			End Set
		End Property

		Public Overridable Property s_CategoryID As String
			Get
				If Me.IsColumnNull(ProductsSchema.CategoryID.FieldName) Then
					Return String.Empty
				Else
					Return MyBase.GetIntegerAsString(ProductsSchema.CategoryID.FieldName)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ProductsSchema.CategoryID.FieldName)
				Else
					Me.CategoryID = MyBase.SetIntegerAsString(ProductsSchema.CategoryID.FieldName, Value)
				End If
			End Set
		End Property

		Public Overridable Property s_QuantityPerUnit As String
			Get
				If Me.IsColumnNull(ProductsSchema.QuantityPerUnit.FieldName) Then
					Return String.Empty
				Else
					Return MyBase.GetStringAsString(ProductsSchema.QuantityPerUnit.FieldName)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ProductsSchema.QuantityPerUnit.FieldName)
				Else
					Me.QuantityPerUnit = MyBase.SetStringAsString(ProductsSchema.QuantityPerUnit.FieldName, Value)
				End If
			End Set
		End Property

		Public Overridable Property s_UnitPrice As String
			Get
				If Me.IsColumnNull(ProductsSchema.UnitPrice.FieldName) Then
					Return String.Empty
				Else
					Return MyBase.GetDecimalAsString(ProductsSchema.UnitPrice.FieldName)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ProductsSchema.UnitPrice.FieldName)
				Else
					Me.UnitPrice = MyBase.SetDecimalAsString(ProductsSchema.UnitPrice.FieldName, Value)
				End If
			End Set
		End Property

		Public Overridable Property s_UnitsInStock As String
			Get
				If Me.IsColumnNull(ProductsSchema.UnitsInStock.FieldName) Then
					Return String.Empty
				Else
					Return MyBase.GetShortAsString(ProductsSchema.UnitsInStock.FieldName)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ProductsSchema.UnitsInStock.FieldName)
				Else
					Me.UnitsInStock = MyBase.SetShortAsString(ProductsSchema.UnitsInStock.FieldName, Value)
				End If
			End Set
		End Property

		Public Overridable Property s_UnitsOnOrder As String
			Get
				If Me.IsColumnNull(ProductsSchema.UnitsOnOrder.FieldName) Then
					Return String.Empty
				Else
					Return MyBase.GetShortAsString(ProductsSchema.UnitsOnOrder.FieldName)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ProductsSchema.UnitsOnOrder.FieldName)
				Else
					Me.UnitsOnOrder = MyBase.SetShortAsString(ProductsSchema.UnitsOnOrder.FieldName, Value)
				End If
			End Set
		End Property

		Public Overridable Property s_ReorderLevel As String
			Get
				If Me.IsColumnNull(ProductsSchema.ReorderLevel.FieldName) Then
					Return String.Empty
				Else
					Return MyBase.GetShortAsString(ProductsSchema.ReorderLevel.FieldName)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ProductsSchema.ReorderLevel.FieldName)
				Else
					Me.ReorderLevel = MyBase.SetShortAsString(ProductsSchema.ReorderLevel.FieldName, Value)
				End If
			End Set
		End Property

		Public Overridable Property s_Discontinued As String
			Get
				If Me.IsColumnNull(ProductsSchema.Discontinued.FieldName) Then
					Return String.Empty
				Else
					Return MyBase.GetBooleanAsString(ProductsSchema.Discontinued.FieldName)
				End If
			End Get
			Set(ByVal Value As String)
				If String.Empty = value Then
					Me.SetColumnNull(ProductsSchema.Discontinued.FieldName)
				Else
					Me.Discontinued = MyBase.SetBooleanAsString(ProductsSchema.Discontinued.FieldName, Value)
				End If
			End Set
		End Property


#End Region

#Region " Where Clause "
    Public Class WhereClause

        Public Sub New(ByVal entity As EasyObject)
            Me._entity = entity
        End Sub
		
		Public ReadOnly Property TearOff As TearOffWhereParameter
			Get
				If _tearOff Is Nothing Then
					_tearOff = new TearOffWhereParameter(Me)
				End If

				Return _tearOff
			End Get
		End Property

		#Region " TearOff's "
		Public class TearOffWhereParameter
		
			Private _clause as WhereClause
			
			Public Sub New(ByVal clause As WhereClause)
				Me._clause = clause
			End Sub

			Public ReadOnly Property ProductID() As WhereParameter
				Get
					Dim wp As WhereParameter = New WhereParameter(ProductsSchema.ProductID)
                    Dim query As NCI.EasyObjects.DynamicQuery = Me._clause._entity.Query
                    query.AddWhereParameter(wp)
					Return wp
				End Get
			End Property

			Public ReadOnly Property ProductName() As WhereParameter
				Get
					Dim wp As WhereParameter = New WhereParameter(ProductsSchema.ProductName)
                    Dim query As NCI.EasyObjects.DynamicQuery = Me._clause._entity.Query
                    query.AddWhereParameter(wp)
					Return wp
				End Get
			End Property

			Public ReadOnly Property SupplierID() As WhereParameter
				Get
					Dim wp As WhereParameter = New WhereParameter(ProductsSchema.SupplierID)
                    Dim query As NCI.EasyObjects.DynamicQuery = Me._clause._entity.Query
                    query.AddWhereParameter(wp)
					Return wp
				End Get
			End Property

			Public ReadOnly Property CategoryID() As WhereParameter
				Get
					Dim wp As WhereParameter = New WhereParameter(ProductsSchema.CategoryID)
                    Dim query As NCI.EasyObjects.DynamicQuery = Me._clause._entity.Query
                    query.AddWhereParameter(wp)
					Return wp
				End Get
			End Property

			Public ReadOnly Property QuantityPerUnit() As WhereParameter
				Get
					Dim wp As WhereParameter = New WhereParameter(ProductsSchema.QuantityPerUnit)
                    Dim query As NCI.EasyObjects.DynamicQuery = Me._clause._entity.Query
                    query.AddWhereParameter(wp)
					Return wp
				End Get
			End Property

			Public ReadOnly Property UnitPrice() As WhereParameter
				Get
					Dim wp As WhereParameter = New WhereParameter(ProductsSchema.UnitPrice)
                    Dim query As NCI.EasyObjects.DynamicQuery = Me._clause._entity.Query
                    query.AddWhereParameter(wp)
					Return wp
				End Get
			End Property

			Public ReadOnly Property UnitsInStock() As WhereParameter
				Get
					Dim wp As WhereParameter = New WhereParameter(ProductsSchema.UnitsInStock)
                    Dim query As NCI.EasyObjects.DynamicQuery = Me._clause._entity.Query
                    query.AddWhereParameter(wp)
					Return wp
				End Get
			End Property

			Public ReadOnly Property UnitsOnOrder() As WhereParameter
				Get
					Dim wp As WhereParameter = New WhereParameter(ProductsSchema.UnitsOnOrder)
                    Dim query As NCI.EasyObjects.DynamicQuery = Me._clause._entity.Query
                    query.AddWhereParameter(wp)
					Return wp
				End Get
			End Property

			Public ReadOnly Property ReorderLevel() As WhereParameter
				Get
					Dim wp As WhereParameter = New WhereParameter(ProductsSchema.ReorderLevel)
                    Dim query As NCI.EasyObjects.DynamicQuery = Me._clause._entity.Query
                    query.AddWhereParameter(wp)
					Return wp
				End Get
			End Property

			Public ReadOnly Property Discontinued() As WhereParameter
				Get
					Dim wp As WhereParameter = New WhereParameter(ProductsSchema.Discontinued)
                    Dim query As NCI.EasyObjects.DynamicQuery = Me._clause._entity.Query
                    query.AddWhereParameter(wp)
					Return wp
				End Get
			End Property

	End Class
	
	#End Region	

		Public ReadOnly Property ProductID() As WhereParameter 
			Get
				If _ProductID_W Is Nothing Then
					_ProductID_W = TearOff.ProductID
				End If
				Return _ProductID_W
			End Get
		End Property

		Public ReadOnly Property ProductName() As WhereParameter 
			Get
				If _ProductName_W Is Nothing Then
					_ProductName_W = TearOff.ProductName
				End If
				Return _ProductName_W
			End Get
		End Property

		Public ReadOnly Property SupplierID() As WhereParameter 
			Get
				If _SupplierID_W Is Nothing Then
					_SupplierID_W = TearOff.SupplierID
				End If
				Return _SupplierID_W
			End Get
		End Property

		Public ReadOnly Property CategoryID() As WhereParameter 
			Get
				If _CategoryID_W Is Nothing Then
					_CategoryID_W = TearOff.CategoryID
				End If
				Return _CategoryID_W
			End Get
		End Property

		Public ReadOnly Property QuantityPerUnit() As WhereParameter 
			Get
				If _QuantityPerUnit_W Is Nothing Then
					_QuantityPerUnit_W = TearOff.QuantityPerUnit
				End If
				Return _QuantityPerUnit_W
			End Get
		End Property

		Public ReadOnly Property UnitPrice() As WhereParameter 
			Get
				If _UnitPrice_W Is Nothing Then
					_UnitPrice_W = TearOff.UnitPrice
				End If
				Return _UnitPrice_W
			End Get
		End Property

		Public ReadOnly Property UnitsInStock() As WhereParameter 
			Get
				If _UnitsInStock_W Is Nothing Then
					_UnitsInStock_W = TearOff.UnitsInStock
				End If
				Return _UnitsInStock_W
			End Get
		End Property

		Public ReadOnly Property UnitsOnOrder() As WhereParameter 
			Get
				If _UnitsOnOrder_W Is Nothing Then
					_UnitsOnOrder_W = TearOff.UnitsOnOrder
				End If
				Return _UnitsOnOrder_W
			End Get
		End Property

		Public ReadOnly Property ReorderLevel() As WhereParameter 
			Get
				If _ReorderLevel_W Is Nothing Then
					_ReorderLevel_W = TearOff.ReorderLevel
				End If
				Return _ReorderLevel_W
			End Get
		End Property

		Public ReadOnly Property Discontinued() As WhereParameter 
			Get
				If _Discontinued_W Is Nothing Then
					_Discontinued_W = TearOff.Discontinued
				End If
				Return _Discontinued_W
			End Get
		End Property

		Private _ProductID_W As WhereParameter = Nothing
		Private _ProductName_W As WhereParameter = Nothing
		Private _SupplierID_W As WhereParameter = Nothing
		Private _CategoryID_W As WhereParameter = Nothing
		Private _QuantityPerUnit_W As WhereParameter = Nothing
		Private _UnitPrice_W As WhereParameter = Nothing
		Private _UnitsInStock_W As WhereParameter = Nothing
		Private _UnitsOnOrder_W As WhereParameter = Nothing
		Private _ReorderLevel_W As WhereParameter = Nothing
		Private _Discontinued_W As WhereParameter = Nothing

		Public Sub WhereClauseReset()

		_ProductID_W = Nothing
		_ProductName_W = Nothing
		_SupplierID_W = Nothing
		_CategoryID_W = Nothing
		_QuantityPerUnit_W = Nothing
		_UnitPrice_W = Nothing
		_UnitsInStock_W = Nothing
		_UnitsOnOrder_W = Nothing
		_ReorderLevel_W = Nothing
		_Discontinued_W = Nothing
			Me._entity.Query.FlushWhereParameters()

		End Sub
	
		Private _entity As EasyObject
		Private _tearOff As TearOffWhereParameter
    End Class	

	Public ReadOnly Property Where() As WhereClause
		Get
			If _whereClause Is Nothing Then
				_whereClause = New WhereClause(Me)
			End If
	
			Return _whereClause
		End Get
	End Property
	
	Private _whereClause As WhereClause = Nothing	
#End Region	

#Region " Aggregate Clause "
    Public Class AggregateClause

        Public Sub New(ByVal entity As EasyObject)
            Me._entity = entity
        End Sub
		
		Public ReadOnly Property TearOff As TearOffAggregateParameter
			Get
				If _tearOff Is Nothing Then
					_tearOff = new TearOffAggregateParameter(Me)
				End If

				Return _tearOff
			End Get
		End Property

		#Region " TearOff's "
		Public class TearOffAggregateParameter
		
			Private _clause as AggregateClause
			
			Public Sub New(ByVal clause As AggregateClause)
				Me._clause = clause
			End Sub

			Public ReadOnly Property ProductID() As AggregateParameter
				Get
					Dim ap As AggregateParameter = New AggregateParameter(ProductsSchema.ProductID)
                    Dim query As NCI.EasyObjects.DynamicQuery = Me._clause._entity.Query
                    query.AddAggregateParameter(ap)
					Return ap
				End Get
			End Property

			Public ReadOnly Property ProductName() As AggregateParameter
				Get
					Dim ap As AggregateParameter = New AggregateParameter(ProductsSchema.ProductName)
                    Dim query As NCI.EasyObjects.DynamicQuery = Me._clause._entity.Query
                    query.AddAggregateParameter(ap)
					Return ap
				End Get
			End Property

			Public ReadOnly Property SupplierID() As AggregateParameter
				Get
					Dim ap As AggregateParameter = New AggregateParameter(ProductsSchema.SupplierID)
                    Dim query As NCI.EasyObjects.DynamicQuery = Me._clause._entity.Query
                    query.AddAggregateParameter(ap)
					Return ap
				End Get
			End Property

			Public ReadOnly Property CategoryID() As AggregateParameter
				Get
					Dim ap As AggregateParameter = New AggregateParameter(ProductsSchema.CategoryID)
                    Dim query As NCI.EasyObjects.DynamicQuery = Me._clause._entity.Query
                    query.AddAggregateParameter(ap)
					Return ap
				End Get
			End Property

			Public ReadOnly Property QuantityPerUnit() As AggregateParameter
				Get
					Dim ap As AggregateParameter = New AggregateParameter(ProductsSchema.QuantityPerUnit)
                    Dim query As NCI.EasyObjects.DynamicQuery = Me._clause._entity.Query
                    query.AddAggregateParameter(ap)
					Return ap
				End Get
			End Property

			Public ReadOnly Property UnitPrice() As AggregateParameter
				Get
					Dim ap As AggregateParameter = New AggregateParameter(ProductsSchema.UnitPrice)
                    Dim query As NCI.EasyObjects.DynamicQuery = Me._clause._entity.Query
                    query.AddAggregateParameter(ap)
					Return ap
				End Get
			End Property

			Public ReadOnly Property UnitsInStock() As AggregateParameter
				Get
					Dim ap As AggregateParameter = New AggregateParameter(ProductsSchema.UnitsInStock)
                    Dim query As NCI.EasyObjects.DynamicQuery = Me._clause._entity.Query
                    query.AddAggregateParameter(ap)
					Return ap
				End Get
			End Property

			Public ReadOnly Property UnitsOnOrder() As AggregateParameter
				Get
					Dim ap As AggregateParameter = New AggregateParameter(ProductsSchema.UnitsOnOrder)
                    Dim query As NCI.EasyObjects.DynamicQuery = Me._clause._entity.Query
                    query.AddAggregateParameter(ap)
					Return ap
				End Get
			End Property

			Public ReadOnly Property ReorderLevel() As AggregateParameter
				Get
					Dim ap As AggregateParameter = New AggregateParameter(ProductsSchema.ReorderLevel)
                    Dim query As NCI.EasyObjects.DynamicQuery = Me._clause._entity.Query
                    query.AddAggregateParameter(ap)
					Return ap
				End Get
			End Property

			Public ReadOnly Property Discontinued() As AggregateParameter
				Get
					Dim ap As AggregateParameter = New AggregateParameter(ProductsSchema.Discontinued)
                    Dim query As NCI.EasyObjects.DynamicQuery = Me._clause._entity.Query
                    query.AddAggregateParameter(ap)
					Return ap
				End Get
			End Property

	End Class
	
	#End Region	

		Public ReadOnly Property ProductID() As AggregateParameter 
			Get
				If _ProductID_W Is Nothing Then
					_ProductID_W = TearOff.ProductID
				End If
				Return _ProductID_W
			End Get
		End Property

		Public ReadOnly Property ProductName() As AggregateParameter 
			Get
				If _ProductName_W Is Nothing Then
					_ProductName_W = TearOff.ProductName
				End If
				Return _ProductName_W
			End Get
		End Property

		Public ReadOnly Property SupplierID() As AggregateParameter 
			Get
				If _SupplierID_W Is Nothing Then
					_SupplierID_W = TearOff.SupplierID
				End If
				Return _SupplierID_W
			End Get
		End Property

		Public ReadOnly Property CategoryID() As AggregateParameter 
			Get
				If _CategoryID_W Is Nothing Then
					_CategoryID_W = TearOff.CategoryID
				End If
				Return _CategoryID_W
			End Get
		End Property

		Public ReadOnly Property QuantityPerUnit() As AggregateParameter 
			Get
				If _QuantityPerUnit_W Is Nothing Then
					_QuantityPerUnit_W = TearOff.QuantityPerUnit
				End If
				Return _QuantityPerUnit_W
			End Get
		End Property

		Public ReadOnly Property UnitPrice() As AggregateParameter 
			Get
				If _UnitPrice_W Is Nothing Then
					_UnitPrice_W = TearOff.UnitPrice
				End If
				Return _UnitPrice_W
			End Get
		End Property

		Public ReadOnly Property UnitsInStock() As AggregateParameter 
			Get
				If _UnitsInStock_W Is Nothing Then
					_UnitsInStock_W = TearOff.UnitsInStock
				End If
				Return _UnitsInStock_W
			End Get
		End Property

		Public ReadOnly Property UnitsOnOrder() As AggregateParameter 
			Get
				If _UnitsOnOrder_W Is Nothing Then
					_UnitsOnOrder_W = TearOff.UnitsOnOrder
				End If
				Return _UnitsOnOrder_W
			End Get
		End Property

		Public ReadOnly Property ReorderLevel() As AggregateParameter 
			Get
				If _ReorderLevel_W Is Nothing Then
					_ReorderLevel_W = TearOff.ReorderLevel
				End If
				Return _ReorderLevel_W
			End Get
		End Property

		Public ReadOnly Property Discontinued() As AggregateParameter 
			Get
				If _Discontinued_W Is Nothing Then
					_Discontinued_W = TearOff.Discontinued
				End If
				Return _Discontinued_W
			End Get
		End Property

		Private _ProductID_W As AggregateParameter = Nothing
		Private _ProductName_W As AggregateParameter = Nothing
		Private _SupplierID_W As AggregateParameter = Nothing
		Private _CategoryID_W As AggregateParameter = Nothing
		Private _QuantityPerUnit_W As AggregateParameter = Nothing
		Private _UnitPrice_W As AggregateParameter = Nothing
		Private _UnitsInStock_W As AggregateParameter = Nothing
		Private _UnitsOnOrder_W As AggregateParameter = Nothing
		Private _ReorderLevel_W As AggregateParameter = Nothing
		Private _Discontinued_W As AggregateParameter = Nothing

		Public Sub AggregateClauseReset()

		_ProductID_W = Nothing
		_ProductName_W = Nothing
		_SupplierID_W = Nothing
		_CategoryID_W = Nothing
		_QuantityPerUnit_W = Nothing
		_UnitPrice_W = Nothing
		_UnitsInStock_W = Nothing
		_UnitsOnOrder_W = Nothing
		_ReorderLevel_W = Nothing
		_Discontinued_W = Nothing
			Me._entity.Query.FlushAggregateParameters()

		End Sub
	
		Private _entity As EasyObject
		Private _tearOff As TearOffAggregateParameter
    End Class	

	Public ReadOnly Property Aggregate() As AggregateClause
		Get
			If _aggregateClause Is Nothing Then
				_aggregateClause = New AggregateClause(Me)
			End If
	
			Return _aggregateClause
		End Get
	End Property
	
	Private _aggregateClause As AggregateClause = Nothing	
#End Region	

End Class


