
' Generated by MyGeneration Version # (1.1.4.0)

Imports System

Public Class Products 
	Inherits _Products

    Public Sub New(ByVal server As String, ByVal useIntegratedSecurity As Boolean, ByVal userID As String, ByVal password As String)
        Me.ConnectionServer = server
        Me.UseIntegratedSecurity = useIntegratedSecurity
        Me.ConnectionUserID = userID
        Me.ConnectionPassword = password
        Me.ConnectionDatabase = "Northwind"
    End Sub

End Class
