/*
'===============================================================================
'  Generated From - CSharp_EasyObject_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL      = SQL_DAAB_StoredProcs.vbgen
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easily done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.1.4.0)

using System;
using System.Data;
using System.Configuration;
using System.Collections;
using System.Collections.Specialized;
using System.Xml;
using System.IO;

using Microsoft.Practices.EnterpriseLibrary.Data;
using NCI.EasyObjects;

namespace EasyObjectsQuickStart.BLL
{

	#region Schema

	public class CustomerDemographicsSchema : NCI.EasyObjects.Schema
	{
		private static ArrayList _entries;
		public static SchemaItem CustomerTypeID = new SchemaItem("CustomerTypeID", DbType.StringFixedLength, SchemaItemJustify.None, 10, false, true, true, false);
		public static SchemaItem CustomerDesc = new SchemaItem("CustomerDesc", DbType.String, SchemaItemJustify.None, 1073741823, true, false, false, false);

		public override ArrayList SchemaEntries
		{
			get
			{
				if (_entries == null )
				{
					_entries = new ArrayList();
					_entries.Add(CustomerDemographicsSchema.CustomerTypeID);
					_entries.Add(CustomerDemographicsSchema.CustomerDesc);
				}
				return _entries;
			}
		}
	}
	#endregion

	public abstract class _CustomerDemographics : EasyObject
	{

		public _CustomerDemographics()
		{
			CustomerDemographicsSchema _schema = new CustomerDemographicsSchema();
			this.SchemaEntries = _schema.SchemaEntries;
			this.SchemaGlobal = "dbo";
		}
		
		public override void FlushData() 	 
		{ 	 
			this._whereClause = null; 	 
			this._aggregateClause = null; 	 
			base.FlushData(); 	 
		}
			   
		/// <summary>
		/// Loads the business object with info from the database, based on the requested primary key.
		/// </summary>
		/// <param name="CustomerTypeID"></param>
		/// <returns>A Boolean indicating success or failure of the query</returns>
		public bool LoadByPrimaryKey(string CustomerTypeID)
		{
			switch(this.DefaultCommandType)
			{
				case CommandType.StoredProcedure:
					ListDictionary parameters = new ListDictionary();

					// Add in parameters
					parameters.Add(CustomerDemographicsSchema.CustomerTypeID.FieldName, CustomerTypeID);

					return base.LoadFromSql(this.SchemaStoredProcedureWithSeparator + "daab_GetCustomerDemographics", parameters, CommandType.StoredProcedure);

				case CommandType.Text:
					this.Query.ClearAll();
					this.Where.WhereClauseReset();
					this.Where.CustomerTypeID.Value = CustomerTypeID;
					return this.Query.Load();

				default:
					throw new ArgumentException("Invalid CommandType", "commandType");
			}
		}
	
		/// <summary>
		/// Loads all records from the table.
		/// </summary>
		/// <returns>A Boolean indicating success or failure of the query</returns>
		public bool LoadAll()
		{
			switch(this.DefaultCommandType)
			{
				case CommandType.StoredProcedure:
					return base.LoadFromSql(this.SchemaStoredProcedureWithSeparator + "daab_GetAllCustomerDemographics", null, CommandType.StoredProcedure);

				case CommandType.Text:
					this.Query.ClearAll();
					this.Where.WhereClauseReset();
					return this.Query.Load();

				default:
					throw new ArgumentException("Invalid CommandType", "commandType");
			}
		}

		/// <summary>
		/// Adds a new record to the internal table.
		/// </summary>
		public override void AddNew()
		{
			base.AddNew();
		}

		protected override DBCommandWrapper GetInsertCommand(CommandType commandType)
		{	
			DBCommandWrapper dbCommandWrapper;

			// Create the Database object, using the default database service. The
			// default database service is determined through configuration.
			Database db = GetDatabase();

			switch(commandType)
			{
				case CommandType.StoredProcedure:
					string sqlCommand = this.SchemaStoredProcedureWithSeparator + "daab_AddCustomerDemographics";
					dbCommandWrapper = db.GetStoredProcCommandWrapper(sqlCommand);

					CreateParameters(dbCommandWrapper);
					
					return dbCommandWrapper;

				case CommandType.Text:
					this.Query.ClearAll();
					this.Where.WhereClauseReset();
					foreach(SchemaItem item in this.SchemaEntries)
					{
						if (!(item.IsAutoKey || item.IsComputed))
						{
							this.Query.AddInsertColumn(item);
						}
					}
					dbCommandWrapper = this.Query.GetInsertCommandWrapper();

					dbCommandWrapper.Command.Parameters.Clear();
					CreateParameters(dbCommandWrapper);
					
					return dbCommandWrapper;

				default:
					throw new ArgumentException("Invalid CommandType", "commandType");
			}
		}

		protected override DBCommandWrapper GetUpdateCommand(CommandType commandType)
		{
			DBCommandWrapper dbCommandWrapper;

			// Create the Database object, using the default database service. The
			// default database service is determined through configuration.
			Database db = GetDatabase();

			switch(commandType)
			{
				case CommandType.StoredProcedure:
					string sqlCommand = this.SchemaStoredProcedureWithSeparator + "daab_UpdateCustomerDemographics";
					dbCommandWrapper = db.GetStoredProcCommandWrapper(sqlCommand);

					dbCommandWrapper.AddInParameter("CustomerTypeID", DbType.StringFixedLength, "CustomerTypeID", DataRowVersion.Current);
					CreateParameters(dbCommandWrapper);
					
					return dbCommandWrapper;

				case CommandType.Text:
					this.Query.ClearAll();
					foreach(SchemaItem item in this.SchemaEntries)
					{
						if (!(item.IsAutoKey || item.IsComputed))
						{
							this.Query.AddUpdateColumn(item);
						}
					}

					this.Where.WhereClauseReset();
					this.Where.CustomerTypeID.Operator = WhereParameter.Operand.Equal;
					dbCommandWrapper = this.Query.GetUpdateCommandWrapper();

					dbCommandWrapper.Command.Parameters.Clear();
					CreateParameters(dbCommandWrapper);
					dbCommandWrapper.AddInParameter("CustomerTypeID", DbType.StringFixedLength, "CustomerTypeID", DataRowVersion.Current);
					
					return dbCommandWrapper;

				default:
					throw new ArgumentException("Invalid CommandType", "commandType");
			}
		}

		protected override DBCommandWrapper GetDeleteCommand(CommandType commandType)
		{
			DBCommandWrapper dbCommandWrapper;

			// Create the Database object, using the default database service. The
			// default database service is determined through configuration.
			Database db = GetDatabase();

			switch(commandType)
			{
				case CommandType.StoredProcedure:
					string sqlCommand = this.SchemaStoredProcedureWithSeparator + "daab_DeleteCustomerDemographics";
					dbCommandWrapper = db.GetStoredProcCommandWrapper(sqlCommand);
					dbCommandWrapper.AddInParameter("CustomerTypeID", DbType.StringFixedLength, "CustomerTypeID", DataRowVersion.Current);
					
					return dbCommandWrapper;

				case CommandType.Text:
					this.Query.ClearAll();
					this.Where.WhereClauseReset();
					this.Where.CustomerTypeID.Operator = WhereParameter.Operand.Equal;
					dbCommandWrapper = this.Query.GetDeleteCommandWrapper();

					dbCommandWrapper.Command.Parameters.Clear();
					dbCommandWrapper.AddInParameter("CustomerTypeID", DbType.StringFixedLength, "CustomerTypeID", DataRowVersion.Current);
					
					return dbCommandWrapper;

				default:
					throw new ArgumentException("Invalid CommandType", "commandType");
			}
		}

		private void CreateParameters(DBCommandWrapper dbCommandWrapper)
		{
			dbCommandWrapper.AddInParameter("CustomerTypeID", DbType.StringFixedLength, "CustomerTypeID", DataRowVersion.Current);
			dbCommandWrapper.AddInParameter("CustomerDesc", DbType.String, "CustomerDesc", DataRowVersion.Current);
		}
		
		#region Properties
		public virtual string CustomerTypeID
		{
			get
			{
				return this.GetString(CustomerDemographicsSchema.CustomerTypeID.FieldName);
	    	}
			set
			{
				this.SetString(CustomerDemographicsSchema.CustomerTypeID.FieldName, value);
			}
		}
		public virtual string CustomerDesc
		{
			get
			{
				return this.GetString(CustomerDemographicsSchema.CustomerDesc.FieldName);
	    	}
			set
			{
				this.SetString(CustomerDemographicsSchema.CustomerDesc.FieldName, value);
			}
		}

		public override string TableName
		{
			get { return "CustomerDemographics"; }
		}
		
		#endregion		
		
		#region String Properties
	
		public virtual string s_CustomerTypeID
	    {
			get
	        {
				return this.IsColumnNull(CustomerDemographicsSchema.CustomerTypeID.FieldName) ? string.Empty : base.GetStringAsString(CustomerDemographicsSchema.CustomerTypeID.FieldName);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(CustomerDemographicsSchema.CustomerTypeID.FieldName);
				else
					this.CustomerTypeID = base.SetStringAsString(CustomerDemographicsSchema.CustomerTypeID.FieldName, value);
			}
		}

		public virtual string s_CustomerDesc
	    {
			get
	        {
				return this.IsColumnNull(CustomerDemographicsSchema.CustomerDesc.FieldName) ? string.Empty : base.GetStringAsString(CustomerDemographicsSchema.CustomerDesc.FieldName);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(CustomerDemographicsSchema.CustomerDesc.FieldName);
				else
					this.CustomerDesc = base.SetStringAsString(CustomerDemographicsSchema.CustomerDesc.FieldName, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(EasyObject entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter CustomerTypeID
				{
					get
					{
							WhereParameter wp = new WhereParameter(CustomerDemographicsSchema.CustomerTypeID);
							this._clause._entity.Query.AddWhereParameter(wp);
							return wp;
					}
				}

				public WhereParameter CustomerDesc
				{
					get
					{
							WhereParameter wp = new WhereParameter(CustomerDemographicsSchema.CustomerDesc);
							this._clause._entity.Query.AddWhereParameter(wp);
							return wp;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter CustomerTypeID
		    {
				get
		        {
					if(_CustomerTypeID_W == null)
	        	    {
						_CustomerTypeID_W = TearOff.CustomerTypeID;
					}
					return _CustomerTypeID_W;
				}
			}

			public WhereParameter CustomerDesc
		    {
				get
		        {
					if(_CustomerDesc_W == null)
	        	    {
						_CustomerDesc_W = TearOff.CustomerDesc;
					}
					return _CustomerDesc_W;
				}
			}

			private WhereParameter _CustomerTypeID_W = null;
			private WhereParameter _CustomerDesc_W = null;

			public void WhereClauseReset()
			{
				_CustomerTypeID_W = null;
				_CustomerDesc_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private EasyObject _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
		
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(EasyObject entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter CustomerTypeID
				{
					get
					{
							AggregateParameter ap = new AggregateParameter(CustomerDemographicsSchema.CustomerTypeID);
							this._clause._entity.Query.AddAggregateParameter(ap);
							return ap;
					}
				}

				public AggregateParameter CustomerDesc
				{
					get
					{
							AggregateParameter ap = new AggregateParameter(CustomerDemographicsSchema.CustomerDesc);
							this._clause._entity.Query.AddAggregateParameter(ap);
							return ap;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter CustomerTypeID
		    {
				get
		        {
					if(_CustomerTypeID_W == null)
	        	    {
						_CustomerTypeID_W = TearOff.CustomerTypeID;
					}
					return _CustomerTypeID_W;
				}
			}

			public AggregateParameter CustomerDesc
		    {
				get
		        {
					if(_CustomerDesc_W == null)
	        	    {
						_CustomerDesc_W = TearOff.CustomerDesc;
					}
					return _CustomerDesc_W;
				}
			}

			private AggregateParameter _CustomerTypeID_W = null;
			private AggregateParameter _CustomerDesc_W = null;

			public void AggregateClauseReset()
			{
				_CustomerTypeID_W = null;
				_CustomerDesc_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private EasyObject _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	}
}
