/*
'===============================================================================
'  Generated From - CSharp_EasyObject_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL      = SQL_DAAB_StoredProcs.vbgen
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easily done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.1.6.0)

using System;
using System.Data;
using System.Configuration;
using System.Collections;
using System.Collections.Specialized;
using System.Xml;
using System.IO;

using Microsoft.Practices.EnterpriseLibrary.Data;
using NCI.EasyObjects;

namespace EasyObjectsQuickStart.BLL
{

	#region Schema

	public class ProductsSchema : NCI.EasyObjects.Schema
	{
		private static ArrayList _entries;
		public static SchemaItem ProductID = new SchemaItem("ProductID", DbType.Int32, true, false, false, true, true, false);
		public static SchemaItem ProductName = new SchemaItem("ProductName", DbType.String, SchemaItemJustify.None, 40, false, false, false, false);
		public static SchemaItem SupplierID = new SchemaItem("SupplierID", DbType.Int32, false, true, false, false, true, false);
		public static SchemaItem CategoryID = new SchemaItem("CategoryID", DbType.Int32, false, true, false, false, true, false);
		public static SchemaItem QuantityPerUnit = new SchemaItem("QuantityPerUnit", DbType.String, SchemaItemJustify.None, 20, true, false, false, false);
		public static SchemaItem UnitPrice = new SchemaItem("UnitPrice", DbType.Currency, false, true, false, false, false, true);
		public static SchemaItem UnitsInStock = new SchemaItem("UnitsInStock", DbType.Int16, false, true, false, false, false, true);
		public static SchemaItem UnitsOnOrder = new SchemaItem("UnitsOnOrder", DbType.Int16, false, true, false, false, false, true);
		public static SchemaItem ReorderLevel = new SchemaItem("ReorderLevel", DbType.Int16, false, true, false, false, false, true);
		public static SchemaItem Discontinued = new SchemaItem("Discontinued", DbType.Boolean, false, false, false, false, false, true);

		public override ArrayList SchemaEntries
		{
			get
			{
				if (_entries == null )
				{
					_entries = new ArrayList();
					_entries.Add(ProductsSchema.ProductID);
					_entries.Add(ProductsSchema.ProductName);
					_entries.Add(ProductsSchema.SupplierID);
					_entries.Add(ProductsSchema.CategoryID);
					_entries.Add(ProductsSchema.QuantityPerUnit);
					_entries.Add(ProductsSchema.UnitPrice);
					_entries.Add(ProductsSchema.UnitsInStock);
					_entries.Add(ProductsSchema.UnitsOnOrder);
					_entries.Add(ProductsSchema.ReorderLevel);
					_entries.Add(ProductsSchema.Discontinued);
				}
				return _entries;
			}
		}
	}
	#endregion

	public abstract class _Products : EasyObject
	{

		public _Products()
		{
			ProductsSchema _schema = new ProductsSchema();
			this.SchemaEntries = _schema.SchemaEntries;
			this.SchemaGlobal = "dbo";
		}
		
		public override void FlushData() 	 
		{ 	 
			this._whereClause = null; 	 
			this._aggregateClause = null; 	 
			base.FlushData(); 	 
		}
			   
		/// <summary>
		/// Loads the business object with info from the database, based on the requested primary key.
		/// </summary>
		/// <param name="ProductID"></param>
		/// <returns>A Boolean indicating success or failure of the query</returns>
		public bool LoadByPrimaryKey(int ProductID)
		{
			switch(this.DefaultCommandType)
			{
				case CommandType.StoredProcedure:
					ListDictionary parameters = new ListDictionary();

					// Add in parameters
					parameters.Add(ProductsSchema.ProductID.FieldName, ProductID);

					return base.LoadFromSql(this.SchemaStoredProcedureWithSeparator + "daab_GetProducts", parameters, CommandType.StoredProcedure);

				case CommandType.Text:
					this.Query.ClearAll();
					this.Where.WhereClauseReset();
					this.Where.ProductID.Value = ProductID;
					return this.Query.Load();

				default:
					throw new ArgumentException("Invalid CommandType", "commandType");
			}
		}
	
		/// <summary>
		/// Loads all records from the table.
		/// </summary>
		/// <returns>A Boolean indicating success or failure of the query</returns>
		public bool LoadAll()
		{
			switch(this.DefaultCommandType)
			{
				case CommandType.StoredProcedure:
					return base.LoadFromSql(this.SchemaStoredProcedureWithSeparator + "daab_GetAllProducts", null, CommandType.StoredProcedure);

				case CommandType.Text:
					this.Query.ClearAll();
					this.Where.WhereClauseReset();
					return this.Query.Load();

				default:
					throw new ArgumentException("Invalid CommandType", "commandType");
			}
		}

		/// <summary>
		/// Adds a new record to the internal table.
		/// </summary>
		public override void AddNew()
		{
			base.AddNew();
		}

		protected override DBCommandWrapper GetInsertCommand(CommandType commandType)
		{	
			DBCommandWrapper dbCommandWrapper;

			// Create the Database object, using the default database service. The
			// default database service is determined through configuration.
			Database db = GetDatabase();

			switch(commandType)
			{
				case CommandType.StoredProcedure:
					string sqlCommand = this.SchemaStoredProcedureWithSeparator + "daab_AddProducts";
					dbCommandWrapper = db.GetStoredProcCommandWrapper(sqlCommand);

					dbCommandWrapper.AddParameter("ProductID", DbType.Int32, 0, ParameterDirection.Output, true, 0, 0, "ProductID", DataRowVersion.Default, Convert.DBNull);
					CreateParameters(dbCommandWrapper);
					
					return dbCommandWrapper;

				case CommandType.Text:
					this.Query.ClearAll();
					this.Where.WhereClauseReset();
					foreach(SchemaItem item in this.SchemaEntries)
					{
						if ((item.IsAutoKey && this.IdentityInsert) || !item.IsAutoKey)
						{
							this.Query.AddInsertColumn(item);
						}
					}
					dbCommandWrapper = this.Query.GetInsertCommandWrapper();

					dbCommandWrapper.Command.Parameters.Clear();
					if (this.IdentityInsert)
					{
						dbCommandWrapper.AddInParameter("ProductID", DbType.Int32, "ProductID", DataRowVersion.Default);
					}
					else
					{
						dbCommandWrapper.AddParameter("ProductID", DbType.Int32, 0, ParameterDirection.Output, true, 0, 0, "ProductID", DataRowVersion.Default, Convert.DBNull);
					}
					CreateParameters(dbCommandWrapper);

					return dbCommandWrapper;

				default:
					throw new ArgumentException("Invalid CommandType", "commandType");
			}
		}

		protected override DBCommandWrapper GetUpdateCommand(CommandType commandType)
		{
			DBCommandWrapper dbCommandWrapper;

			// Create the Database object, using the default database service. The
			// default database service is determined through configuration.
			Database db = GetDatabase();

			switch(commandType)
			{
				case CommandType.StoredProcedure:
					string sqlCommand = this.SchemaStoredProcedureWithSeparator + "daab_UpdateProducts";
					dbCommandWrapper = db.GetStoredProcCommandWrapper(sqlCommand);

					dbCommandWrapper.AddInParameter("ProductID", DbType.Int32, "ProductID", DataRowVersion.Current);
					CreateParameters(dbCommandWrapper);
					
					return dbCommandWrapper;

				case CommandType.Text:
					this.Query.ClearAll();
					foreach(SchemaItem item in this.SchemaEntries)
					{
						if (!(item.IsAutoKey || item.IsComputed))
						{
							this.Query.AddUpdateColumn(item);
						}
					}

					this.Where.WhereClauseReset();
					this.Where.ProductID.Operator = WhereParameter.Operand.Equal;
					dbCommandWrapper = this.Query.GetUpdateCommandWrapper();

					dbCommandWrapper.Command.Parameters.Clear();
					CreateParameters(dbCommandWrapper);
					dbCommandWrapper.AddInParameter("ProductID", DbType.Int32, "ProductID", DataRowVersion.Current);
					
					return dbCommandWrapper;

				default:
					throw new ArgumentException("Invalid CommandType", "commandType");
			}
		}

		protected override DBCommandWrapper GetDeleteCommand(CommandType commandType)
		{
			DBCommandWrapper dbCommandWrapper;

			// Create the Database object, using the default database service. The
			// default database service is determined through configuration.
			Database db = GetDatabase();

			switch(commandType)
			{
				case CommandType.StoredProcedure:
					string sqlCommand = this.SchemaStoredProcedureWithSeparator + "daab_DeleteProducts";
					dbCommandWrapper = db.GetStoredProcCommandWrapper(sqlCommand);
					dbCommandWrapper.AddInParameter("ProductID", DbType.Int32, "ProductID", DataRowVersion.Current);
					
					return dbCommandWrapper;

				case CommandType.Text:
					this.Query.ClearAll();
					this.Where.WhereClauseReset();
					this.Where.ProductID.Operator = WhereParameter.Operand.Equal;
					dbCommandWrapper = this.Query.GetDeleteCommandWrapper();

					dbCommandWrapper.Command.Parameters.Clear();
					dbCommandWrapper.AddInParameter("ProductID", DbType.Int32, "ProductID", DataRowVersion.Current);
					
					return dbCommandWrapper;

				default:
					throw new ArgumentException("Invalid CommandType", "commandType");
			}
		}

		private void CreateParameters(DBCommandWrapper dbCommandWrapper)
		{
			dbCommandWrapper.AddInParameter("ProductName", DbType.String, "ProductName", DataRowVersion.Current);
			dbCommandWrapper.AddInParameter("SupplierID", DbType.Int32, "SupplierID", DataRowVersion.Current);
			dbCommandWrapper.AddInParameter("CategoryID", DbType.Int32, "CategoryID", DataRowVersion.Current);
			dbCommandWrapper.AddInParameter("QuantityPerUnit", DbType.String, "QuantityPerUnit", DataRowVersion.Current);
			dbCommandWrapper.AddInParameter("UnitPrice", DbType.Currency, "UnitPrice", DataRowVersion.Current);
			dbCommandWrapper.AddInParameter("UnitsInStock", DbType.Int16, "UnitsInStock", DataRowVersion.Current);
			dbCommandWrapper.AddInParameter("UnitsOnOrder", DbType.Int16, "UnitsOnOrder", DataRowVersion.Current);
			dbCommandWrapper.AddInParameter("ReorderLevel", DbType.Int16, "ReorderLevel", DataRowVersion.Current);
			dbCommandWrapper.AddInParameter("Discontinued", DbType.Boolean, "Discontinued", DataRowVersion.Current);
		}
		
		#region Properties
		public virtual int ProductID
		{
			get
			{
				return this.GetInteger(ProductsSchema.ProductID.FieldName);
	    	}
			set
			{
				this.SetInteger(ProductsSchema.ProductID.FieldName, value);
			}
		}
		public virtual string ProductName
		{
			get
			{
				return this.GetString(ProductsSchema.ProductName.FieldName);
	    	}
			set
			{
				this.SetString(ProductsSchema.ProductName.FieldName, value);
			}
		}
		public virtual int SupplierID
		{
			get
			{
				return this.GetInteger(ProductsSchema.SupplierID.FieldName);
	    	}
			set
			{
				this.SetInteger(ProductsSchema.SupplierID.FieldName, value);
			}
		}
		public virtual int CategoryID
		{
			get
			{
				return this.GetInteger(ProductsSchema.CategoryID.FieldName);
	    	}
			set
			{
				this.SetInteger(ProductsSchema.CategoryID.FieldName, value);
			}
		}
		public virtual string QuantityPerUnit
		{
			get
			{
				return this.GetString(ProductsSchema.QuantityPerUnit.FieldName);
	    	}
			set
			{
				this.SetString(ProductsSchema.QuantityPerUnit.FieldName, value);
			}
		}
		public virtual decimal UnitPrice
		{
			get
			{
				return this.GetDecimal(ProductsSchema.UnitPrice.FieldName);
	    	}
			set
			{
				this.SetDecimal(ProductsSchema.UnitPrice.FieldName, value);
			}
		}
		public virtual short UnitsInStock
		{
			get
			{
				return this.GetShort(ProductsSchema.UnitsInStock.FieldName);
	    	}
			set
			{
				this.SetShort(ProductsSchema.UnitsInStock.FieldName, value);
			}
		}
		public virtual short UnitsOnOrder
		{
			get
			{
				return this.GetShort(ProductsSchema.UnitsOnOrder.FieldName);
	    	}
			set
			{
				this.SetShort(ProductsSchema.UnitsOnOrder.FieldName, value);
			}
		}
		public virtual short ReorderLevel
		{
			get
			{
				return this.GetShort(ProductsSchema.ReorderLevel.FieldName);
	    	}
			set
			{
				this.SetShort(ProductsSchema.ReorderLevel.FieldName, value);
			}
		}
		public virtual bool Discontinued
		{
			get
			{
				return this.GetBoolean(ProductsSchema.Discontinued.FieldName);
	    	}
			set
			{
				this.SetBoolean(ProductsSchema.Discontinued.FieldName, value);
			}
		}

		public override string TableName
		{
			get { return "Products"; }
		}
		
		#endregion		
		
		#region String Properties
	
		public virtual string s_ProductID
	    {
			get
	        {
				return this.IsColumnNull(ProductsSchema.ProductID.FieldName) ? string.Empty : base.GetIntegerAsString(ProductsSchema.ProductID.FieldName);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ProductsSchema.ProductID.FieldName);
				else
					this.ProductID = base.SetIntegerAsString(ProductsSchema.ProductID.FieldName, value);
			}
		}

		public virtual string s_ProductName
	    {
			get
	        {
				return this.IsColumnNull(ProductsSchema.ProductName.FieldName) ? string.Empty : base.GetStringAsString(ProductsSchema.ProductName.FieldName);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ProductsSchema.ProductName.FieldName);
				else
					this.ProductName = base.SetStringAsString(ProductsSchema.ProductName.FieldName, value);
			}
		}

		public virtual string s_SupplierID
	    {
			get
	        {
				return this.IsColumnNull(ProductsSchema.SupplierID.FieldName) ? string.Empty : base.GetIntegerAsString(ProductsSchema.SupplierID.FieldName);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ProductsSchema.SupplierID.FieldName);
				else
					this.SupplierID = base.SetIntegerAsString(ProductsSchema.SupplierID.FieldName, value);
			}
		}

		public virtual string s_CategoryID
	    {
			get
	        {
				return this.IsColumnNull(ProductsSchema.CategoryID.FieldName) ? string.Empty : base.GetIntegerAsString(ProductsSchema.CategoryID.FieldName);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ProductsSchema.CategoryID.FieldName);
				else
					this.CategoryID = base.SetIntegerAsString(ProductsSchema.CategoryID.FieldName, value);
			}
		}

		public virtual string s_QuantityPerUnit
	    {
			get
	        {
				return this.IsColumnNull(ProductsSchema.QuantityPerUnit.FieldName) ? string.Empty : base.GetStringAsString(ProductsSchema.QuantityPerUnit.FieldName);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ProductsSchema.QuantityPerUnit.FieldName);
				else
					this.QuantityPerUnit = base.SetStringAsString(ProductsSchema.QuantityPerUnit.FieldName, value);
			}
		}

		public virtual string s_UnitPrice
	    {
			get
	        {
				return this.IsColumnNull(ProductsSchema.UnitPrice.FieldName) ? string.Empty : base.GetDecimalAsString(ProductsSchema.UnitPrice.FieldName);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ProductsSchema.UnitPrice.FieldName);
				else
					this.UnitPrice = base.SetDecimalAsString(ProductsSchema.UnitPrice.FieldName, value);
			}
		}

		public virtual string s_UnitsInStock
	    {
			get
	        {
				return this.IsColumnNull(ProductsSchema.UnitsInStock.FieldName) ? string.Empty : base.GetShortAsString(ProductsSchema.UnitsInStock.FieldName);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ProductsSchema.UnitsInStock.FieldName);
				else
					this.UnitsInStock = base.SetShortAsString(ProductsSchema.UnitsInStock.FieldName, value);
			}
		}

		public virtual string s_UnitsOnOrder
	    {
			get
	        {
				return this.IsColumnNull(ProductsSchema.UnitsOnOrder.FieldName) ? string.Empty : base.GetShortAsString(ProductsSchema.UnitsOnOrder.FieldName);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ProductsSchema.UnitsOnOrder.FieldName);
				else
					this.UnitsOnOrder = base.SetShortAsString(ProductsSchema.UnitsOnOrder.FieldName, value);
			}
		}

		public virtual string s_ReorderLevel
	    {
			get
	        {
				return this.IsColumnNull(ProductsSchema.ReorderLevel.FieldName) ? string.Empty : base.GetShortAsString(ProductsSchema.ReorderLevel.FieldName);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ProductsSchema.ReorderLevel.FieldName);
				else
					this.ReorderLevel = base.SetShortAsString(ProductsSchema.ReorderLevel.FieldName, value);
			}
		}

		public virtual string s_Discontinued
	    {
			get
	        {
				return this.IsColumnNull(ProductsSchema.Discontinued.FieldName) ? string.Empty : base.GetBooleanAsString(ProductsSchema.Discontinued.FieldName);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ProductsSchema.Discontinued.FieldName);
				else
					this.Discontinued = base.SetBooleanAsString(ProductsSchema.Discontinued.FieldName, value);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(EasyObject entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter ProductID
				{
					get
					{
							WhereParameter wp = new WhereParameter(ProductsSchema.ProductID);
							this._clause._entity.Query.AddWhereParameter(wp);
							return wp;
					}
				}

				public WhereParameter ProductName
				{
					get
					{
							WhereParameter wp = new WhereParameter(ProductsSchema.ProductName);
							this._clause._entity.Query.AddWhereParameter(wp);
							return wp;
					}
				}

				public WhereParameter SupplierID
				{
					get
					{
							WhereParameter wp = new WhereParameter(ProductsSchema.SupplierID);
							this._clause._entity.Query.AddWhereParameter(wp);
							return wp;
					}
				}

				public WhereParameter CategoryID
				{
					get
					{
							WhereParameter wp = new WhereParameter(ProductsSchema.CategoryID);
							this._clause._entity.Query.AddWhereParameter(wp);
							return wp;
					}
				}

				public WhereParameter QuantityPerUnit
				{
					get
					{
							WhereParameter wp = new WhereParameter(ProductsSchema.QuantityPerUnit);
							this._clause._entity.Query.AddWhereParameter(wp);
							return wp;
					}
				}

				public WhereParameter UnitPrice
				{
					get
					{
							WhereParameter wp = new WhereParameter(ProductsSchema.UnitPrice);
							this._clause._entity.Query.AddWhereParameter(wp);
							return wp;
					}
				}

				public WhereParameter UnitsInStock
				{
					get
					{
							WhereParameter wp = new WhereParameter(ProductsSchema.UnitsInStock);
							this._clause._entity.Query.AddWhereParameter(wp);
							return wp;
					}
				}

				public WhereParameter UnitsOnOrder
				{
					get
					{
							WhereParameter wp = new WhereParameter(ProductsSchema.UnitsOnOrder);
							this._clause._entity.Query.AddWhereParameter(wp);
							return wp;
					}
				}

				public WhereParameter ReorderLevel
				{
					get
					{
							WhereParameter wp = new WhereParameter(ProductsSchema.ReorderLevel);
							this._clause._entity.Query.AddWhereParameter(wp);
							return wp;
					}
				}

				public WhereParameter Discontinued
				{
					get
					{
							WhereParameter wp = new WhereParameter(ProductsSchema.Discontinued);
							this._clause._entity.Query.AddWhereParameter(wp);
							return wp;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter ProductID
		    {
				get
		        {
					if(_ProductID_W == null)
	        	    {
						_ProductID_W = TearOff.ProductID;
					}
					return _ProductID_W;
				}
			}

			public WhereParameter ProductName
		    {
				get
		        {
					if(_ProductName_W == null)
	        	    {
						_ProductName_W = TearOff.ProductName;
					}
					return _ProductName_W;
				}
			}

			public WhereParameter SupplierID
		    {
				get
		        {
					if(_SupplierID_W == null)
	        	    {
						_SupplierID_W = TearOff.SupplierID;
					}
					return _SupplierID_W;
				}
			}

			public WhereParameter CategoryID
		    {
				get
		        {
					if(_CategoryID_W == null)
	        	    {
						_CategoryID_W = TearOff.CategoryID;
					}
					return _CategoryID_W;
				}
			}

			public WhereParameter QuantityPerUnit
		    {
				get
		        {
					if(_QuantityPerUnit_W == null)
	        	    {
						_QuantityPerUnit_W = TearOff.QuantityPerUnit;
					}
					return _QuantityPerUnit_W;
				}
			}

			public WhereParameter UnitPrice
		    {
				get
		        {
					if(_UnitPrice_W == null)
	        	    {
						_UnitPrice_W = TearOff.UnitPrice;
					}
					return _UnitPrice_W;
				}
			}

			public WhereParameter UnitsInStock
		    {
				get
		        {
					if(_UnitsInStock_W == null)
	        	    {
						_UnitsInStock_W = TearOff.UnitsInStock;
					}
					return _UnitsInStock_W;
				}
			}

			public WhereParameter UnitsOnOrder
		    {
				get
		        {
					if(_UnitsOnOrder_W == null)
	        	    {
						_UnitsOnOrder_W = TearOff.UnitsOnOrder;
					}
					return _UnitsOnOrder_W;
				}
			}

			public WhereParameter ReorderLevel
		    {
				get
		        {
					if(_ReorderLevel_W == null)
	        	    {
						_ReorderLevel_W = TearOff.ReorderLevel;
					}
					return _ReorderLevel_W;
				}
			}

			public WhereParameter Discontinued
		    {
				get
		        {
					if(_Discontinued_W == null)
	        	    {
						_Discontinued_W = TearOff.Discontinued;
					}
					return _Discontinued_W;
				}
			}

			private WhereParameter _ProductID_W = null;
			private WhereParameter _ProductName_W = null;
			private WhereParameter _SupplierID_W = null;
			private WhereParameter _CategoryID_W = null;
			private WhereParameter _QuantityPerUnit_W = null;
			private WhereParameter _UnitPrice_W = null;
			private WhereParameter _UnitsInStock_W = null;
			private WhereParameter _UnitsOnOrder_W = null;
			private WhereParameter _ReorderLevel_W = null;
			private WhereParameter _Discontinued_W = null;

			public void WhereClauseReset()
			{
				_ProductID_W = null;
				_ProductName_W = null;
				_SupplierID_W = null;
				_CategoryID_W = null;
				_QuantityPerUnit_W = null;
				_UnitPrice_W = null;
				_UnitsInStock_W = null;
				_UnitsOnOrder_W = null;
				_ReorderLevel_W = null;
				_Discontinued_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private EasyObject _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
		
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(EasyObject entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter ProductID
				{
					get
					{
							AggregateParameter ap = new AggregateParameter(ProductsSchema.ProductID);
							this._clause._entity.Query.AddAggregateParameter(ap);
							return ap;
					}
				}

				public AggregateParameter ProductName
				{
					get
					{
							AggregateParameter ap = new AggregateParameter(ProductsSchema.ProductName);
							this._clause._entity.Query.AddAggregateParameter(ap);
							return ap;
					}
				}

				public AggregateParameter SupplierID
				{
					get
					{
							AggregateParameter ap = new AggregateParameter(ProductsSchema.SupplierID);
							this._clause._entity.Query.AddAggregateParameter(ap);
							return ap;
					}
				}

				public AggregateParameter CategoryID
				{
					get
					{
							AggregateParameter ap = new AggregateParameter(ProductsSchema.CategoryID);
							this._clause._entity.Query.AddAggregateParameter(ap);
							return ap;
					}
				}

				public AggregateParameter QuantityPerUnit
				{
					get
					{
							AggregateParameter ap = new AggregateParameter(ProductsSchema.QuantityPerUnit);
							this._clause._entity.Query.AddAggregateParameter(ap);
							return ap;
					}
				}

				public AggregateParameter UnitPrice
				{
					get
					{
							AggregateParameter ap = new AggregateParameter(ProductsSchema.UnitPrice);
							this._clause._entity.Query.AddAggregateParameter(ap);
							return ap;
					}
				}

				public AggregateParameter UnitsInStock
				{
					get
					{
							AggregateParameter ap = new AggregateParameter(ProductsSchema.UnitsInStock);
							this._clause._entity.Query.AddAggregateParameter(ap);
							return ap;
					}
				}

				public AggregateParameter UnitsOnOrder
				{
					get
					{
							AggregateParameter ap = new AggregateParameter(ProductsSchema.UnitsOnOrder);
							this._clause._entity.Query.AddAggregateParameter(ap);
							return ap;
					}
				}

				public AggregateParameter ReorderLevel
				{
					get
					{
							AggregateParameter ap = new AggregateParameter(ProductsSchema.ReorderLevel);
							this._clause._entity.Query.AddAggregateParameter(ap);
							return ap;
					}
				}

				public AggregateParameter Discontinued
				{
					get
					{
							AggregateParameter ap = new AggregateParameter(ProductsSchema.Discontinued);
							this._clause._entity.Query.AddAggregateParameter(ap);
							return ap;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter ProductID
		    {
				get
		        {
					if(_ProductID_W == null)
	        	    {
						_ProductID_W = TearOff.ProductID;
					}
					return _ProductID_W;
				}
			}

			public AggregateParameter ProductName
		    {
				get
		        {
					if(_ProductName_W == null)
	        	    {
						_ProductName_W = TearOff.ProductName;
					}
					return _ProductName_W;
				}
			}

			public AggregateParameter SupplierID
		    {
				get
		        {
					if(_SupplierID_W == null)
	        	    {
						_SupplierID_W = TearOff.SupplierID;
					}
					return _SupplierID_W;
				}
			}

			public AggregateParameter CategoryID
		    {
				get
		        {
					if(_CategoryID_W == null)
	        	    {
						_CategoryID_W = TearOff.CategoryID;
					}
					return _CategoryID_W;
				}
			}

			public AggregateParameter QuantityPerUnit
		    {
				get
		        {
					if(_QuantityPerUnit_W == null)
	        	    {
						_QuantityPerUnit_W = TearOff.QuantityPerUnit;
					}
					return _QuantityPerUnit_W;
				}
			}

			public AggregateParameter UnitPrice
		    {
				get
		        {
					if(_UnitPrice_W == null)
	        	    {
						_UnitPrice_W = TearOff.UnitPrice;
					}
					return _UnitPrice_W;
				}
			}

			public AggregateParameter UnitsInStock
		    {
				get
		        {
					if(_UnitsInStock_W == null)
	        	    {
						_UnitsInStock_W = TearOff.UnitsInStock;
					}
					return _UnitsInStock_W;
				}
			}

			public AggregateParameter UnitsOnOrder
		    {
				get
		        {
					if(_UnitsOnOrder_W == null)
	        	    {
						_UnitsOnOrder_W = TearOff.UnitsOnOrder;
					}
					return _UnitsOnOrder_W;
				}
			}

			public AggregateParameter ReorderLevel
		    {
				get
		        {
					if(_ReorderLevel_W == null)
	        	    {
						_ReorderLevel_W = TearOff.ReorderLevel;
					}
					return _ReorderLevel_W;
				}
			}

			public AggregateParameter Discontinued
		    {
				get
		        {
					if(_Discontinued_W == null)
	        	    {
						_Discontinued_W = TearOff.Discontinued;
					}
					return _Discontinued_W;
				}
			}

			private AggregateParameter _ProductID_W = null;
			private AggregateParameter _ProductName_W = null;
			private AggregateParameter _SupplierID_W = null;
			private AggregateParameter _CategoryID_W = null;
			private AggregateParameter _QuantityPerUnit_W = null;
			private AggregateParameter _UnitPrice_W = null;
			private AggregateParameter _UnitsInStock_W = null;
			private AggregateParameter _UnitsOnOrder_W = null;
			private AggregateParameter _ReorderLevel_W = null;
			private AggregateParameter _Discontinued_W = null;

			public void AggregateClauseReset()
			{
				_ProductID_W = null;
				_ProductName_W = null;
				_SupplierID_W = null;
				_CategoryID_W = null;
				_QuantityPerUnit_W = null;
				_UnitPrice_W = null;
				_UnitsInStock_W = null;
				_UnitsOnOrder_W = null;
				_ReorderLevel_W = null;
				_Discontinued_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private EasyObject _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	}
}
