/*
'===============================================================================
'  Generated From - CSharp_EasyObject_BusinessEntity.vbgen
' 
'  ** IMPORTANT  ** 
'  How to Generate your stored procedures:
' 
'  SQL      = SQL_DAAB_StoredProcs.vbgen
'  
'  This object is 'abstract' which means you need to inherit from it to be able
'  to instantiate it.  This is very easily done. You can override properties and
'  methods in your derived class, this allows you to regenerate this class at any
'  time and not worry about overwriting custom code. 
'
'  NEVER EDIT THIS FILE.
'
'  public class YourObject :  _YourObject
'  {
'
'  }
'
'===============================================================================
*/

// Generated by MyGeneration Version # (1.1.6.0)

using System;
using System.Data;
using System.Configuration;
using System.Collections;
using System.Collections.Specialized;
using System.Xml;
using System.IO;

using Microsoft.Practices.EnterpriseLibrary.Data;
using NCI.EasyObjects;

namespace NCI.EasyObjects.Tests.SQL
{

	#region Schema

	public class ComputedTestSchema : NCI.EasyObjects.Schema
	{
		private static ArrayList _entries;
		public static SchemaItem RecordID = new SchemaItem("RecordID", DbType.Int32, true, false, false, true, false, false);
		public static SchemaItem Integer1 = new SchemaItem("Integer1", DbType.Int32, false, true, false, false, false, false);
		public static SchemaItem Integer2 = new SchemaItem("Integer2", DbType.Int32, false, true, false, false, false, false);
		public static SchemaItem String1 = new SchemaItem("String1", DbType.AnsiString, SchemaItemJustify.None, 5, true, false, false, false);
		public static SchemaItem String2 = new SchemaItem("String2", DbType.AnsiString, SchemaItemJustify.None, 5, true, false, false, false);
		public static SchemaItem Computed1 = new SchemaItem("Computed1", DbType.Int32, false, true, true, false, false, false);
		public static SchemaItem Computed2 = new SchemaItem("Computed2", DbType.AnsiString, SchemaItemJustify.None, 11, true, false, false, false);

		public override ArrayList SchemaEntries
		{
			get
			{
				if (_entries == null )
				{
					_entries = new ArrayList();
					_entries.Add(ComputedTestSchema.RecordID);
					_entries.Add(ComputedTestSchema.Integer1);
					_entries.Add(ComputedTestSchema.Integer2);
					_entries.Add(ComputedTestSchema.String1);
					_entries.Add(ComputedTestSchema.String2);
					ComputedTestSchema.Computed1.IsComputed = true;
					_entries.Add(ComputedTestSchema.Computed1);
					ComputedTestSchema.Computed2.IsComputed = true;
					_entries.Add(ComputedTestSchema.Computed2);
				}
				return _entries;
			}
		}
	}
	#endregion

	public abstract class _ComputedTest : EasyObject
	{

		public _ComputedTest()
		{
			ComputedTestSchema _schema = new ComputedTestSchema();
			this.SchemaEntries = _schema.SchemaEntries;
			this.SchemaGlobal = "dbo";
		}
		
		public override void FlushData() 	 
		{ 	 
			this._whereClause = null; 	 
			this._aggregateClause = null; 	 
			base.FlushData(); 	 
		}
			   
		/// <summary>
		/// Loads the business object with info from the database, based on the requested primary key.
		/// </summary>
		/// <param name="RecordID"></param>
		/// <returns>A Boolean indicating success or failure of the query</returns>
		public bool LoadByPrimaryKey(int RecordID)
		{
			switch(this.DefaultCommandType)
			{
				case CommandType.StoredProcedure:
					ListDictionary parameters = new ListDictionary();

					// Add in parameters
					parameters.Add(ComputedTestSchema.RecordID.FieldName, RecordID);

					return base.LoadFromSql(this.SchemaStoredProcedureWithSeparator + "daab_GetComputedTest", parameters, CommandType.StoredProcedure);

				case CommandType.Text:
					this.Query.ClearAll();
					this.Where.WhereClauseReset();
					this.Where.RecordID.Value = RecordID;
					return this.Query.Load();

				default:
					throw new ArgumentException("Invalid CommandType", "commandType");
			}
		}
	
		/// <summary>
		/// Loads all records from the table.
		/// </summary>
		/// <returns>A Boolean indicating success or failure of the query</returns>
		public bool LoadAll()
		{
			switch(this.DefaultCommandType)
			{
				case CommandType.StoredProcedure:
					return base.LoadFromSql(this.SchemaStoredProcedureWithSeparator + "daab_GetAllComputedTest", null, CommandType.StoredProcedure);

				case CommandType.Text:
					this.Query.ClearAll();
					this.Where.WhereClauseReset();
					return this.Query.Load();

				default:
					throw new ArgumentException("Invalid CommandType", "commandType");
			}
		}

		/// <summary>
		/// Adds a new record to the internal table.
		/// </summary>
		public override void AddNew()
		{
			base.AddNew();
		}

		protected override DBCommandWrapper GetInsertCommand(CommandType commandType)
		{	
			DBCommandWrapper dbCommandWrapper;

			// Create the Database object, using the default database service. The
			// default database service is determined through configuration.
			Database db = GetDatabase();

			switch(commandType)
			{
				case CommandType.StoredProcedure:
					string sqlCommand = this.SchemaStoredProcedureWithSeparator + "daab_AddComputedTest";
					dbCommandWrapper = db.GetStoredProcCommandWrapper(sqlCommand);

					dbCommandWrapper.AddParameter("RecordID", DbType.Int32, 0, ParameterDirection.Output, true, 0, 0, "RecordID", DataRowVersion.Default, Convert.DBNull);
					CreateParameters(dbCommandWrapper);
					
					return dbCommandWrapper;

				case CommandType.Text:
					this.Query.ClearAll();
					this.Where.WhereClauseReset();
					foreach(SchemaItem item in this.SchemaEntries)
					{
						if (!item.IsComputed)
						{
							if ((item.IsAutoKey && this.IdentityInsert) || !item.IsAutoKey)
							{
								this.Query.AddInsertColumn(item);
							}
						}
					}
					dbCommandWrapper = this.Query.GetInsertCommandWrapper();

					dbCommandWrapper.Command.Parameters.Clear();
					if (this.IdentityInsert)
					{
						dbCommandWrapper.AddInParameter("RecordID", DbType.Int32, "RecordID", DataRowVersion.Default);
					}
					else
					{
						dbCommandWrapper.AddParameter("RecordID", DbType.Int32, 0, ParameterDirection.Output, true, 0, 0, "RecordID", DataRowVersion.Default, Convert.DBNull);
					}
					CreateParameters(dbCommandWrapper);

					return dbCommandWrapper;

				default:
					throw new ArgumentException("Invalid CommandType", "commandType");
			}
		}

		protected override DBCommandWrapper GetUpdateCommand(CommandType commandType)
		{
			DBCommandWrapper dbCommandWrapper;

			// Create the Database object, using the default database service. The
			// default database service is determined through configuration.
			Database db = GetDatabase();

			switch(commandType)
			{
				case CommandType.StoredProcedure:
					string sqlCommand = this.SchemaStoredProcedureWithSeparator + "daab_UpdateComputedTest";
					dbCommandWrapper = db.GetStoredProcCommandWrapper(sqlCommand);

					dbCommandWrapper.AddInParameter("RecordID", DbType.Int32, "RecordID", DataRowVersion.Current);
					CreateParameters(dbCommandWrapper);
					
					return dbCommandWrapper;

				case CommandType.Text:
					this.Query.ClearAll();
					foreach(SchemaItem item in this.SchemaEntries)
					{
						if (!(item.IsAutoKey || item.IsComputed))
						{
							this.Query.AddUpdateColumn(item);
						}
					}

					this.Where.WhereClauseReset();
					this.Where.RecordID.Operator = WhereParameter.Operand.Equal;
					dbCommandWrapper = this.Query.GetUpdateCommandWrapper();

					dbCommandWrapper.Command.Parameters.Clear();
					CreateParameters(dbCommandWrapper);
					dbCommandWrapper.AddInParameter("RecordID", DbType.Int32, "RecordID", DataRowVersion.Current);
					
					return dbCommandWrapper;

				default:
					throw new ArgumentException("Invalid CommandType", "commandType");
			}
		}

		protected override DBCommandWrapper GetDeleteCommand(CommandType commandType)
		{
			DBCommandWrapper dbCommandWrapper;

			// Create the Database object, using the default database service. The
			// default database service is determined through configuration.
			Database db = GetDatabase();

			switch(commandType)
			{
				case CommandType.StoredProcedure:
					string sqlCommand = this.SchemaStoredProcedureWithSeparator + "daab_DeleteComputedTest";
					dbCommandWrapper = db.GetStoredProcCommandWrapper(sqlCommand);
					dbCommandWrapper.AddInParameter("RecordID", DbType.Int32, "RecordID", DataRowVersion.Current);
					
					return dbCommandWrapper;

				case CommandType.Text:
					this.Query.ClearAll();
					this.Where.WhereClauseReset();
					this.Where.RecordID.Operator = WhereParameter.Operand.Equal;
					dbCommandWrapper = this.Query.GetDeleteCommandWrapper();

					dbCommandWrapper.Command.Parameters.Clear();
					dbCommandWrapper.AddInParameter("RecordID", DbType.Int32, "RecordID", DataRowVersion.Current);
					
					return dbCommandWrapper;

				default:
					throw new ArgumentException("Invalid CommandType", "commandType");
			}
		}

		private void CreateParameters(DBCommandWrapper dbCommandWrapper)
		{
			dbCommandWrapper.AddInParameter("Integer1", DbType.Int32, "Integer1", DataRowVersion.Current);
			dbCommandWrapper.AddInParameter("Integer2", DbType.Int32, "Integer2", DataRowVersion.Current);
			dbCommandWrapper.AddInParameter("String1", DbType.AnsiString, "String1", DataRowVersion.Current);
			dbCommandWrapper.AddInParameter("String2", DbType.AnsiString, "String2", DataRowVersion.Current);
			dbCommandWrapper.AddParameter("Computed1", DbType.Int32, ParameterDirection.Output, "Computed1", DataRowVersion.Current, null);
			dbCommandWrapper.AddParameter("Computed2", DbType.AnsiString, 11, ParameterDirection.Output, true, 0, 0, "Computed2", DataRowVersion.Current, null);
		}
		
		#region Properties
		public virtual int RecordID
		{
			get
			{
				return this.GetInteger(ComputedTestSchema.RecordID.FieldName);
	    	}
			set
			{
				this.SetInteger(ComputedTestSchema.RecordID.FieldName, value);
			}
		}
		public virtual int Integer1
		{
			get
			{
				return this.GetInteger(ComputedTestSchema.Integer1.FieldName);
	    	}
			set
			{
				this.SetInteger(ComputedTestSchema.Integer1.FieldName, value);
			}
		}
		public virtual int Integer2
		{
			get
			{
				return this.GetInteger(ComputedTestSchema.Integer2.FieldName);
	    	}
			set
			{
				this.SetInteger(ComputedTestSchema.Integer2.FieldName, value);
			}
		}
		public virtual string String1
		{
			get
			{
				return this.GetString(ComputedTestSchema.String1.FieldName);
	    	}
			set
			{
				this.SetString(ComputedTestSchema.String1.FieldName, value);
			}
		}
		public virtual string String2
		{
			get
			{
				return this.GetString(ComputedTestSchema.String2.FieldName);
	    	}
			set
			{
				this.SetString(ComputedTestSchema.String2.FieldName, value);
			}
		}
		public virtual int Computed1
		{
			get
			{
				return this.GetInteger(ComputedTestSchema.Computed1.FieldName);
	    	}
			set
			{
				this.SetInteger(ComputedTestSchema.Computed1.FieldName, value);
			}
		}
		public virtual string Computed2
		{
			get
			{
				return this.GetString(ComputedTestSchema.Computed2.FieldName);
	    	}
			set
			{
				this.SetString(ComputedTestSchema.Computed2.FieldName, value);
			}
		}

		public override string TableName
		{
			get { return "ComputedTest"; }
		}
		
		#endregion		
		
		#region String Properties
	
		public virtual string s_RecordID
	    {
			get
	        {
				return this.IsColumnNull(ComputedTestSchema.RecordID.FieldName) ? string.Empty : base.GetIntegerAsString(ComputedTestSchema.RecordID.FieldName);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ComputedTestSchema.RecordID.FieldName);
				else
					this.RecordID = base.SetIntegerAsString(ComputedTestSchema.RecordID.FieldName, value);
			}
		}

		public virtual string s_Integer1
	    {
			get
	        {
				return this.IsColumnNull(ComputedTestSchema.Integer1.FieldName) ? string.Empty : base.GetIntegerAsString(ComputedTestSchema.Integer1.FieldName);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ComputedTestSchema.Integer1.FieldName);
				else
					this.Integer1 = base.SetIntegerAsString(ComputedTestSchema.Integer1.FieldName, value);
			}
		}

		public virtual string s_Integer2
	    {
			get
	        {
				return this.IsColumnNull(ComputedTestSchema.Integer2.FieldName) ? string.Empty : base.GetIntegerAsString(ComputedTestSchema.Integer2.FieldName);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ComputedTestSchema.Integer2.FieldName);
				else
					this.Integer2 = base.SetIntegerAsString(ComputedTestSchema.Integer2.FieldName, value);
			}
		}

		public virtual string s_String1
	    {
			get
	        {
				return this.IsColumnNull(ComputedTestSchema.String1.FieldName) ? string.Empty : base.GetStringAsString(ComputedTestSchema.String1.FieldName);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ComputedTestSchema.String1.FieldName);
				else
					this.String1 = base.SetStringAsString(ComputedTestSchema.String1.FieldName, value);
			}
		}

		public virtual string s_String2
	    {
			get
	        {
				return this.IsColumnNull(ComputedTestSchema.String2.FieldName) ? string.Empty : base.GetStringAsString(ComputedTestSchema.String2.FieldName);
			}
			set
	        {
				if(string.Empty == value)
					this.SetColumnNull(ComputedTestSchema.String2.FieldName);
				else
					this.String2 = base.SetStringAsString(ComputedTestSchema.String2.FieldName, value);
			}
		}

		public virtual string s_Computed1
	    {
			get
	        {
				return this.IsColumnNull(ComputedTestSchema.Computed1.FieldName) ? string.Empty : base.GetIntegerAsString(ComputedTestSchema.Computed1.FieldName);
			}
		}

		public virtual string s_Computed2
	    {
			get
	        {
				return this.IsColumnNull(ComputedTestSchema.Computed2.FieldName) ? string.Empty : base.GetStringAsString(ComputedTestSchema.Computed2.FieldName);
			}
		}


		#endregion		
	
		#region Where Clause
		public class WhereClause
		{
			public WhereClause(EasyObject entity)
			{
				this._entity = entity;
			}
			
			public TearOffWhereParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffWhereParameter(this);
					}

					return _tearOff;
				}
			}

			#region TearOff's
			public class TearOffWhereParameter
			{
				public TearOffWhereParameter(WhereClause clause)
				{
					this._clause = clause;
				}
				
				
				public WhereParameter RecordID
				{
					get
					{
							WhereParameter wp = new WhereParameter(ComputedTestSchema.RecordID);
							this._clause._entity.Query.AddWhereParameter(wp);
							return wp;
					}
				}

				public WhereParameter Integer1
				{
					get
					{
							WhereParameter wp = new WhereParameter(ComputedTestSchema.Integer1);
							this._clause._entity.Query.AddWhereParameter(wp);
							return wp;
					}
				}

				public WhereParameter Integer2
				{
					get
					{
							WhereParameter wp = new WhereParameter(ComputedTestSchema.Integer2);
							this._clause._entity.Query.AddWhereParameter(wp);
							return wp;
					}
				}

				public WhereParameter String1
				{
					get
					{
							WhereParameter wp = new WhereParameter(ComputedTestSchema.String1);
							this._clause._entity.Query.AddWhereParameter(wp);
							return wp;
					}
				}

				public WhereParameter String2
				{
					get
					{
							WhereParameter wp = new WhereParameter(ComputedTestSchema.String2);
							this._clause._entity.Query.AddWhereParameter(wp);
							return wp;
					}
				}

				public WhereParameter Computed1
				{
					get
					{
							WhereParameter wp = new WhereParameter(ComputedTestSchema.Computed1);
							this._clause._entity.Query.AddWhereParameter(wp);
							return wp;
					}
				}

				public WhereParameter Computed2
				{
					get
					{
							WhereParameter wp = new WhereParameter(ComputedTestSchema.Computed2);
							this._clause._entity.Query.AddWhereParameter(wp);
							return wp;
					}
				}


				private WhereClause _clause;
			}
			#endregion
		
			public WhereParameter RecordID
		    {
				get
		        {
					if(_RecordID_W == null)
	        	    {
						_RecordID_W = TearOff.RecordID;
					}
					return _RecordID_W;
				}
			}

			public WhereParameter Integer1
		    {
				get
		        {
					if(_Integer1_W == null)
	        	    {
						_Integer1_W = TearOff.Integer1;
					}
					return _Integer1_W;
				}
			}

			public WhereParameter Integer2
		    {
				get
		        {
					if(_Integer2_W == null)
	        	    {
						_Integer2_W = TearOff.Integer2;
					}
					return _Integer2_W;
				}
			}

			public WhereParameter String1
		    {
				get
		        {
					if(_String1_W == null)
	        	    {
						_String1_W = TearOff.String1;
					}
					return _String1_W;
				}
			}

			public WhereParameter String2
		    {
				get
		        {
					if(_String2_W == null)
	        	    {
						_String2_W = TearOff.String2;
					}
					return _String2_W;
				}
			}

			public WhereParameter Computed1
		    {
				get
		        {
					if(_Computed1_W == null)
	        	    {
						_Computed1_W = TearOff.Computed1;
					}
					return _Computed1_W;
				}
			}

			public WhereParameter Computed2
		    {
				get
		        {
					if(_Computed2_W == null)
	        	    {
						_Computed2_W = TearOff.Computed2;
					}
					return _Computed2_W;
				}
			}

			private WhereParameter _RecordID_W = null;
			private WhereParameter _Integer1_W = null;
			private WhereParameter _Integer2_W = null;
			private WhereParameter _String1_W = null;
			private WhereParameter _String2_W = null;
			private WhereParameter _Computed1_W = null;
			private WhereParameter _Computed2_W = null;

			public void WhereClauseReset()
			{
				_RecordID_W = null;
				_Integer1_W = null;
				_Integer2_W = null;
				_String1_W = null;
				_String2_W = null;
				_Computed1_W = null;
				_Computed2_W = null;

				this._entity.Query.FlushWhereParameters();

			}
	
			private EasyObject _entity;
			private TearOffWhereParameter _tearOff;
			
		}
	
		public WhereClause Where
		{
			get
			{
				if(_whereClause == null)
				{
					_whereClause = new WhereClause(this);
				}
		
				return _whereClause;
			}
		}
		
		private WhereClause _whereClause = null;	
		#endregion
		
		#region Aggregate Clause
		public class AggregateClause
		{
			public AggregateClause(EasyObject entity)
			{
				this._entity = entity;
			}
			
			public TearOffAggregateParameter TearOff
			{
				get
				{
					if(_tearOff == null)
					{
						_tearOff = new TearOffAggregateParameter(this);
					}

					return _tearOff;
				}
			}

			#region TearOff's
			public class TearOffAggregateParameter
			{
				public TearOffAggregateParameter(AggregateClause clause)
				{
					this._clause = clause;
				}
				
				
				public AggregateParameter RecordID
				{
					get
					{
							AggregateParameter ap = new AggregateParameter(ComputedTestSchema.RecordID);
							this._clause._entity.Query.AddAggregateParameter(ap);
							return ap;
					}
				}

				public AggregateParameter Integer1
				{
					get
					{
							AggregateParameter ap = new AggregateParameter(ComputedTestSchema.Integer1);
							this._clause._entity.Query.AddAggregateParameter(ap);
							return ap;
					}
				}

				public AggregateParameter Integer2
				{
					get
					{
							AggregateParameter ap = new AggregateParameter(ComputedTestSchema.Integer2);
							this._clause._entity.Query.AddAggregateParameter(ap);
							return ap;
					}
				}

				public AggregateParameter String1
				{
					get
					{
							AggregateParameter ap = new AggregateParameter(ComputedTestSchema.String1);
							this._clause._entity.Query.AddAggregateParameter(ap);
							return ap;
					}
				}

				public AggregateParameter String2
				{
					get
					{
							AggregateParameter ap = new AggregateParameter(ComputedTestSchema.String2);
							this._clause._entity.Query.AddAggregateParameter(ap);
							return ap;
					}
				}

				public AggregateParameter Computed1
				{
					get
					{
							AggregateParameter ap = new AggregateParameter(ComputedTestSchema.Computed1);
							this._clause._entity.Query.AddAggregateParameter(ap);
							return ap;
					}
				}

				public AggregateParameter Computed2
				{
					get
					{
							AggregateParameter ap = new AggregateParameter(ComputedTestSchema.Computed2);
							this._clause._entity.Query.AddAggregateParameter(ap);
							return ap;
					}
				}


				private AggregateClause _clause;
			}
			#endregion
		
			public AggregateParameter RecordID
		    {
				get
		        {
					if(_RecordID_W == null)
	        	    {
						_RecordID_W = TearOff.RecordID;
					}
					return _RecordID_W;
				}
			}

			public AggregateParameter Integer1
		    {
				get
		        {
					if(_Integer1_W == null)
	        	    {
						_Integer1_W = TearOff.Integer1;
					}
					return _Integer1_W;
				}
			}

			public AggregateParameter Integer2
		    {
				get
		        {
					if(_Integer2_W == null)
	        	    {
						_Integer2_W = TearOff.Integer2;
					}
					return _Integer2_W;
				}
			}

			public AggregateParameter String1
		    {
				get
		        {
					if(_String1_W == null)
	        	    {
						_String1_W = TearOff.String1;
					}
					return _String1_W;
				}
			}

			public AggregateParameter String2
		    {
				get
		        {
					if(_String2_W == null)
	        	    {
						_String2_W = TearOff.String2;
					}
					return _String2_W;
				}
			}

			public AggregateParameter Computed1
		    {
				get
		        {
					if(_Computed1_W == null)
	        	    {
						_Computed1_W = TearOff.Computed1;
					}
					return _Computed1_W;
				}
			}

			public AggregateParameter Computed2
		    {
				get
		        {
					if(_Computed2_W == null)
	        	    {
						_Computed2_W = TearOff.Computed2;
					}
					return _Computed2_W;
				}
			}

			private AggregateParameter _RecordID_W = null;
			private AggregateParameter _Integer1_W = null;
			private AggregateParameter _Integer2_W = null;
			private AggregateParameter _String1_W = null;
			private AggregateParameter _String2_W = null;
			private AggregateParameter _Computed1_W = null;
			private AggregateParameter _Computed2_W = null;

			public void AggregateClauseReset()
			{
				_RecordID_W = null;
				_Integer1_W = null;
				_Integer2_W = null;
				_String1_W = null;
				_String2_W = null;
				_Computed1_W = null;
				_Computed2_W = null;

				this._entity.Query.FlushAggregateParameters();

			}
	
			private EasyObject _entity;
			private TearOffAggregateParameter _tearOff;
			
		}
	
		public AggregateClause Aggregate
		{
			get
			{
				if(_aggregateClause == null)
				{
					_aggregateClause = new AggregateClause(this);
				}
		
				return _aggregateClause;
			}
		}
		
		private AggregateClause _aggregateClause = null;	
		#endregion
	}
}
